import Login1 from '../PageObjects/Login1';
import { deviceViewport, extraTimeOut, Timeout } from '../Utils.js';
import methods from '../../support/Common_Method.js'
import locators from '../../support/Locators.js'
import dayjs from 'dayjs';

const nowTime = dayjs().format('H:m:s');
const new_campaign = `New Campaign Pause_${nowTime}`;

describe('Adpilot Smart reach', () => {

    beforeEach(() => {

        cy.viewport(deviceViewport);

        cy.on('uncaught:exception', (err, runnable) => {
            return false;
        });

        //login before run test
        Login1();

    })

    it('Campaign - To Add , Edit Rule , Publish Rule and Delete Rule', () => {

        const nowTime = dayjs().format('H:m:s');
        const new_campaign = `New Campaign_${nowTime}`;

        cy.wait(Timeout.md)
        methods.scrollWithXpath(locators.Account_Pagetitle)
        methods.assertElementContainsTextxpath(locators.Account_Pagetitle, 'All Accounts')
        methods.VisibilityofElement(locators.account_pageloaded)
        cy.wait(Timeout.sm)
        methods.clickElementByXPath(locators.Adpilot)
        methods.VisibilityofElementXpath(locators.SmartReach)
        methods.clickElementByXPath(locators.Add_new_rule)
        methods.clickElementByXPath(locators.Campaign)
        methods.clickElementByXPath(locators.select_Campaign)
        methods.clickElementByXPath(locators.select_Campaign_value)
        methods.clickElementByXPath(locators.select_Campaign_value1)
        methods.clickElementByXPath(locators.select_Campaign_value2)
        methods.clickElementByXPath(locators.adpilot_editicon)
        methods.ClearAndTypeWithXpath(locators.adpilot_edit_searchbar, new_campaign)
        methods.clickElementByXPath(locators.Campaign)
        methods.clickElementByXPath(locators.adpilot_publish)
        methods.assertElementContainsText(locators.notification_popup, "SuccessRule Successfully Created!")
        methods.clickElementByXPath(locators.adpilot_arrow_left)
        cy.wait(Timeout.sm)
        cy.xpath(`//h4[text()="${new_campaign}"]`, { timeout: extraTimeOut }).click({ force: true })
        cy.wait(Timeout.sm)
        methods.clickElementByXPath(locators.All_account_toogle)
        methods.clickElementByXPath(locators.campaign_add_filter)
        methods.clickElementByXPath(locators.Add_Filters_value)
        methods.typeElementByXPath(locators.Add_Filters_value_searchbar, "Company Country ISO Code")
        methods.clickElementByXPath(locators.Add_Filters_value1)
        cy.wait(Timeout.sm)
        methods.clickElementByXPath(locators.account_filter)
        methods.clickElementByXPath(locators.Apply1)
        methods.ClearAndTypeWithXpath(locators.total_clicks_cap, "3")
        methods.ClearAndTypeWithXpath(locators.total_clicks_cap1, "500")
        methods.clickElementByXPath(locators.campaign_add_filter)
        methods.clickElementByXPath(locators.Add_Filters_value)
        methods.typeElementByXPath(locators.Add_Filters_value_searchbar, "Company Country ISO Code")
        methods.clickElementByXPath(locators.Add_Filters_value1)
        cy.wait(Timeout.sm)
        methods.clickElementByXPath(locators.account_filter)
        methods.clickElementByXPath(locators.Apply1)
        methods.ClearAndTypeWithXpath(locators.total_clicks_cap2, "3")
        methods.ClearAndTypeWithXpath(locators.total_clicks_cap3, "500")
        methods.clickElementByXPath(locators.campaign_add_filter)
        methods.clickElementByXPath(locators.Add_Filters_value)
        methods.typeElementByXPath(locators.Add_Filters_value_searchbar, "Company Country ISO Code")
        methods.clickElementByXPath(locators.Add_Filters_value1)
        cy.wait(Timeout.sm)
        methods.clickElementByXPath(locators.account_filter)
        methods.clickElementByXPath(locators.Apply1)
        methods.ClearAndTypeWithXpath(locators.total_clicks_cap4, "3")
        methods.ClearAndTypeWithXpath(locators.total_clicks_cap5, "500")
        cy.wait(Timeout.sm)
        methods.clickElementByXPath(locators.adpilot_arrow_left)
        cy.wait(Timeout.sm)
        cy.xpath(`//h4[text()="${new_campaign}"]//following::button[1]`, { timeout: extraTimeOut }).click({ force: true })
        methods.clickElementByXPath(locators.Remove_rule)
        cy.wait(Timeout.xs)
        methods.clickElementByXPath(locators.Ok)
        methods.assertElementContainsText(locators.notification_popup, "SuccessRule Successfully Deleted!")
    })

    it('To discard the changes made', () => {
        const nowTime = dayjs().format('H:m:s');
        const new_campaign = `New Campaign_${nowTime}`;

        cy.wait(Timeout.md)
        methods.scrollWithXpath(locators.Account_Pagetitle)
        methods.assertElementContainsTextxpath(locators.Account_Pagetitle, 'All Accounts')
        methods.VisibilityofElement(locators.account_pageloaded)
        cy.wait(Timeout.sm)
        methods.clickElementByXPath(locators.Adpilot)
        methods.VisibilityofElementXpath(locators.SmartReach)
        methods.clickElementByXPath(locators.Add_new_rule)
        methods.clickElementByXPath(locators.Campaign)
        methods.clickElementByXPath(locators.select_Campaign)
        methods.clickElementByXPath(locators.select_Campaign_value)
        methods.clickElementByXPath(locators.select_Campaign_value1)
        methods.clickElementByXPath(locators.select_Campaign_value2)
        methods.clickElementByXPath(locators.adpilot_editicon)
        methods.ClearAndTypeWithXpath(locators.adpilot_edit_searchbar, new_campaign)
        methods.clickElementByXPath(locators.Campaign)
        methods.clickElementByXPath(locators.adpilot_publish)
        methods.assertElementContainsText(locators.notification_popup, "SuccessRule Successfully Created!")
        cy.wait(Timeout.sm)
        methods.clickElementByXPath(locators.adpilot_arrow_left)
        cy.wait(Timeout.sm)
        cy.xpath(`//h4[text()="${new_campaign}"]`, { timeout: extraTimeOut }).click({ force: true })
        cy.wait(Timeout.sm)
        methods.clickElementByXPath(locators.All_account_toogle)
        methods.clickElementByXPath(locators.campaign_add_filter)
        methods.clickElementByXPath(locators.Add_Filters_value)
        methods.typeElementByXPath(locators.Add_Filters_value_searchbar, "Company Country ISO Code")
        methods.clickElementByXPath(locators.Add_Filters_value1)
        cy.wait(Timeout.sm)
        methods.clickElementByXPath(locators.account_filter)
        methods.clickElementByXPath(locators.Apply1)
        methods.ClearAndTypeWithXpath(locators.total_clicks_cap, "3")
        methods.ClearAndTypeWithXpath(locators.total_clicks_cap1, "500")
        methods.clickElementByXPath(locators.discard_changes)
        methods.NotVisibilityofElementXpath(locators.advanced_custome_rule)
        methods.clickElementByXPath(locators.Campaign_MoreOption)
        methods.clickElementByXPath(locators.delete)
        cy.wait(Timeout.xs)
        methods.clickElementByXPath(locators.Ok)
        methods.assertElementContainsText(locators.notification_popup, "SuccessRule Successfully Deleted!")
    })

    it('Campaign Group - To Add , Edit Rule , Publish Rule, and delete Rule', () => {
        const nowTime = dayjs().format('H:m:s');
        const new_campaign = `New Group Campaign_${nowTime}`;

        cy.wait(Timeout.md)
        methods.scrollWithXpath(locators.Account_Pagetitle)
        methods.assertElementContainsTextxpath(locators.Account_Pagetitle, 'All Accounts')
        methods.VisibilityofElement(locators.account_pageloaded)
        cy.wait(Timeout.sm)
        methods.clickElementByXPath(locators.Adpilot)
        methods.VisibilityofElementXpath(locators.SmartReach)
        methods.clickElementByXPath(locators.Add_new_rule)
        cy.wait(Timeout.sm)
        methods.clickElementByXPath(locators.campaign_group)
        methods.clickElementByXPath(locators.select_campaign_group)
        methods.clickElementByXPath(locators.select_Campaigngroup_value)
        methods.clickElementByXPath(locators.select_Campaigngroup_value1)
        methods.clickElementByXPath(locators.select_Campaigngroup_value2)
        methods.clickElementByXPath(locators.adpilot_editicon)
        methods.ClearAndTypeWithXpath(locators.adpilot_edit_searchbar, new_campaign)
        methods.clickElementByXPath(locators.campaign_group)
        methods.clickElementByXPath(locators.adpilot_publish)
        methods.assertElementContainsText(locators.notification_popup, "SuccessRule Successfully Created!")
        cy.wait(Timeout.xs)
        methods.clickElementByXPath(locators.adpilot_arrow_left)
        cy.wait(Timeout.sm)
        cy.xpath(`//h4[text()="${new_campaign}"]`, { timeout: extraTimeOut }).click({ force: true })
        cy.wait(Timeout.sm)
        methods.clickElementByXPath(locators.All_account_toogle)
        methods.clickElementByXPath(locators.campaign_add_filter)
        methods.clickElementByXPath(locators.Add_Filters_value)
        methods.typeElementByXPath(locators.Add_Filters_value_searchbar, "Company Country ISO Code")
        methods.clickElementByXPath(locators.Add_Filters_value1)
        cy.wait(Timeout.sm)
        methods.clickElementByXPath(locators.account_filter)
        methods.clickElementByXPath(locators.Apply1)
        methods.ClearAndTypeWithXpath(locators.total_clicks_cap, "3")
        methods.ClearAndTypeWithXpath(locators.total_clicks_cap1, "1000")
        methods.clickElementByXPath(locators.campaign_add_filter)
        methods.clickElementByXPath(locators.Add_Filters_value)
        methods.typeElementByXPath(locators.Add_Filters_value_searchbar, "Company Country ISO Code")
        methods.clickElementByXPath(locators.Add_Filters_value1)
        cy.wait(Timeout.sm)
        methods.clickElementByXPath(locators.account_filter)
        methods.clickElementByXPath(locators.Apply1)
        methods.ClearAndTypeWithXpath(locators.total_clicks_cap2, "3")
        methods.ClearAndTypeWithXpath(locators.total_clicks_cap3, "1000")
        methods.clickElementByXPath(locators.campaign_add_filter)
        methods.clickElementByXPath(locators.Add_Filters_value)
        methods.typeElementByXPath(locators.Add_Filters_value_searchbar, "Company Country ISO Code")
        methods.clickElementByXPath(locators.Add_Filters_value1)
        cy.wait(Timeout.sm)
        methods.clickElementByXPath(locators.account_filter)
        methods.clickElementByXPath(locators.Apply1)
        methods.ClearAndTypeWithXpath(locators.total_clicks_cap4, "3")
        methods.ClearAndTypeWithXpath(locators.total_clicks_cap5, "1000")
        cy.wait(Timeout.sm)
        methods.clickElementByXPath(locators.adpilot_arrow_left)
        cy.wait(Timeout.sm)
        cy.xpath(`//h4[text()="${new_campaign}"]//following::button[1]`, { timeout: extraTimeOut }).click({ force: true })
        methods.clickElementByXPath(locators.Remove_rule)
        cy.wait(Timeout.xs)
        methods.clickElementByXPath(locators.Ok)
        methods.assertElementContainsText(locators.notification_popup, "SuccessRule Successfully Deleted!")
    })

    it('To discard the changes made - Campaign group', () => {
        const nowTime = dayjs().format('H:m:s');
        const new_campaign = `New Group Campaign_${nowTime}`;

        cy.wait(Timeout.md)
        methods.scrollWithXpath(locators.Account_Pagetitle)
        methods.assertElementContainsTextxpath(locators.Account_Pagetitle, 'All Accounts')
        methods.VisibilityofElement(locators.account_pageloaded)
        cy.wait(Timeout.sm)
        methods.clickElementByXPath(locators.Adpilot)
        methods.VisibilityofElementXpath(locators.SmartReach)
        methods.clickElementByXPath(locators.Add_new_rule)
        cy.wait(Timeout.sm)
        methods.clickElementByXPath(locators.campaign_group)
        methods.clickElementByXPath(locators.select_campaign_group)
        methods.clickElementByXPath(locators.select_Campaigngroup_value)
        methods.clickElementByXPath(locators.select_Campaigngroup_value1)
        methods.clickElementByXPath(locators.select_Campaigngroup_value2)
        methods.clickElementByXPath(locators.adpilot_editicon)
        methods.ClearAndTypeWithXpath(locators.adpilot_edit_searchbar, new_campaign)
        methods.clickElementByXPath(locators.campaign_group)
        methods.clickElementByXPath(locators.adpilot_publish)
        methods.assertElementContainsText(locators.notification_popup, "SuccessRule Successfully Created!")
        cy.wait(Timeout.sm)
        methods.clickElementByXPath(locators.adpilot_arrow_left)
        cy.wait(Timeout.sm)
        cy.xpath(`//h4[text()="${new_campaign}"]`, { timeout: extraTimeOut }).click({ force: true })
        cy.wait(Timeout.sm)
        methods.clickElementByXPath(locators.All_account_toogle)
        methods.clickElementByXPath(locators.campaign_add_filter)
        methods.clickElementByXPath(locators.Add_Filters_value)
        methods.typeElementByXPath(locators.Add_Filters_value_searchbar, "Company Country ISO Code")
        methods.clickElementByXPath(locators.Add_Filters_value1)
        cy.wait(Timeout.sm)
        methods.clickElementByXPath(locators.account_filter)
        methods.clickElementByXPath(locators.Apply1)
        methods.ClearAndTypeWithXpath(locators.total_clicks_cap, "3")
        methods.ClearAndTypeWithXpath(locators.total_clicks_cap1, "1000")
        methods.clickElementByXPath(locators.discard_changes)
        methods.NotVisibilityofElementXpath(locators.advanced_custome_rule)
        methods.clickElementByXPath(locators.Campaign_MoreOption)
        methods.clickElementByXPath(locators.delete)
        cy.wait(Timeout.xs)
        methods.clickElementByXPath(locators.Ok)
        methods.assertElementContainsText(locators.notification_popup, "SuccessRule Successfully Deleted!")
    })

    it('All ad accounts - To Add , Edit Rule , Publish Rule, and delete Rule', () => {
        const nowTime = dayjs().format('H:m:s');
        const Add_campaign = `All Ad Accounts_${nowTime}`;

        cy.wait(Timeout.md)
        methods.scrollWithXpath(locators.Account_Pagetitle)
        methods.assertElementContainsTextxpath(locators.Account_Pagetitle, 'All Accounts')
        methods.VisibilityofElement(locators.account_pageloaded)
        cy.wait(Timeout.sm)
        methods.clickElementByXPath(locators.Adpilot)
        methods.VisibilityofElementXpath(locators.SmartReach)
        methods.clickElementByXPath(locators.Add_new_rule)
        cy.wait(Timeout.sm)
        methods.clickElementByXPath(locators.All_Ad_Account)
        methods.clickElementByXPath(locators.adpilot_editicon)
        methods.ClearAndTypeWithXpath(locators.adpilot_edit_searchbar, Add_campaign)
        methods.clickElementByXPath(locators.All_Ad_Account)
        methods.clickElementByXPath(locators.adpilot_publish)
        methods.assertElementContainsText(locators.notification_popup, "SuccessRule Successfully Created!")
        cy.wait(Timeout.sm)
        methods.clickElementByXPath(locators.adpilot_arrow_left)
        cy.wait(Timeout.sm)
        cy.xpath(`//h4[text()="${Add_campaign}"]`, { timeout: extraTimeOut }).click({ force: true })
        cy.wait(Timeout.sm)
        methods.clickElementByXPath(locators.All_account_toogle)
        methods.clickElementByXPath(locators.campaign_add_filter)
        methods.clickElementByXPath(locators.Add_Filters_value)
        methods.typeElementByXPath(locators.Add_Filters_value_searchbar, "Company Country ISO Code")
        methods.clickElementByXPath(locators.Add_Filters_value1)
        cy.wait(Timeout.sm)
        methods.clickElementByXPath(locators.account_filter)
        methods.clickElementByXPath(locators.Apply1)
        methods.ClearAndTypeWithXpath(locators.total_clicks_cap, "3")
        methods.ClearAndTypeWithXpath(locators.total_clicks_cap1, "1000")
        methods.clickElementByXPath(locators.campaign_add_filter)
        methods.clickElementByXPath(locators.Add_Filters_value)
        methods.typeElementByXPath(locators.Add_Filters_value_searchbar, "Company Country ISO Code")
        methods.clickElementByXPath(locators.Add_Filters_value1)
        cy.wait(Timeout.sm)
        methods.clickElementByXPath(locators.account_filter)
        methods.clickElementByXPath(locators.Apply1)
        methods.ClearAndTypeWithXpath(locators.total_clicks_cap2, "3")
        methods.ClearAndTypeWithXpath(locators.total_clicks_cap3, "1000")
        methods.clickElementByXPath(locators.campaign_add_filter)
        methods.clickElementByXPath(locators.Add_Filters_value)
        methods.typeElementByXPath(locators.Add_Filters_value_searchbar, "Company Country ISO Code")
        methods.clickElementByXPath(locators.Add_Filters_value1)
        cy.wait(Timeout.sm)
        methods.clickElementByXPath(locators.account_filter)
        methods.clickElementByXPath(locators.Apply1)
        methods.ClearAndTypeWithXpath(locators.total_clicks_cap4, "3")
        methods.ClearAndTypeWithXpath(locators.total_clicks_cap5, "1000")
        cy.wait(Timeout.sm)
        methods.clickElementByXPath(locators.adpilot_arrow_left)
        cy.wait(Timeout.sm)
        cy.xpath(`//h4[text()="${Add_campaign}"]//following::button[1]`, { timeout: extraTimeOut }).click({ force: true })
        methods.clickElementByXPath(locators.Remove_rule)
        cy.wait(Timeout.xs)
        methods.clickElementByXPath(locators.Ok)
        methods.assertElementContainsText(locators.notification_popup, "SuccessRule Successfully Deleted!")
    })

    it('To discard the changes made  - All ad accounts', () => {
        const nowTime = dayjs().format('H:m:s');
        const Add_campaign = `All Ad Accounts_${nowTime}`;

        cy.wait(Timeout.md)
        methods.scrollWithXpath(locators.Account_Pagetitle)
        methods.assertElementContainsTextxpath(locators.Account_Pagetitle, 'All Accounts')
        methods.VisibilityofElement(locators.account_pageloaded)
        cy.wait(Timeout.sm)
        methods.clickElementByXPath(locators.Adpilot)
        methods.VisibilityofElementXpath(locators.SmartReach)
        methods.clickElementByXPath(locators.Add_new_rule)
        cy.wait(Timeout.sm)
        methods.clickElementByXPath(locators.All_Ad_Account)
        methods.clickElementByXPath(locators.adpilot_editicon)
        methods.ClearAndTypeWithXpath(locators.adpilot_edit_searchbar, Add_campaign)
        methods.clickElementByXPath(locators.All_Ad_Account)
        methods.clickElementByXPath(locators.adpilot_publish)
        methods.assertElementContainsText(locators.notification_popup, "SuccessRule Successfully Created!")
        cy.wait(Timeout.sm)
        methods.clickElementByXPath(locators.adpilot_arrow_left)
        cy.wait(Timeout.sm)
        cy.xpath(`//h4[text()="${Add_campaign}"]`, { timeout: extraTimeOut }).click({ force: true })
        cy.wait(Timeout.sm)
        methods.clickElementByXPath(locators.All_account_toogle)
        methods.clickElementByXPath(locators.campaign_add_filter)
        methods.clickElementByXPath(locators.Add_Filters_value)
        methods.typeElementByXPath(locators.Add_Filters_value_searchbar, "Company Country ISO Code")
        methods.clickElementByXPath(locators.Add_Filters_value1)
        cy.wait(Timeout.sm)
        methods.clickElementByXPath(locators.account_filter)
        methods.clickElementByXPath(locators.Apply1)
        methods.ClearAndTypeWithXpath(locators.total_clicks_cap, "3")
        methods.ClearAndTypeWithXpath(locators.total_clicks_cap1, "1000")
        methods.clickElementByXPath(locators.discard_changes)
        methods.NotVisibilityofElementXpath(locators.advanced_custome_rule)
        methods.clickElementByXPath(locators.Campaign_MoreOption)
        methods.clickElementByXPath(locators.delete)
        cy.wait(Timeout.xs)
        methods.clickElementByXPath(locators.Ok)
        methods.assertElementContainsText(locators.notification_popup, "SuccessRule Successfully Deleted!")
    })

    it('To verify whether the pause functionality is working has expected', () => {

        cy.wait(Timeout.md)
        methods.scrollWithXpath(locators.Account_Pagetitle)
        methods.assertElementContainsTextxpath(locators.Account_Pagetitle, 'All Accounts')
        methods.VisibilityofElement(locators.account_pageloaded)
        cy.wait(Timeout.sm)
        methods.clickElementByXPath(locators.Adpilot)
        methods.VisibilityofElementXpath(locators.SmartReach)
        methods.clickElementByXPath(locators.Add_new_rule)
        methods.clickElementByXPath(locators.Campaign)
        methods.clickElementByXPath(locators.select_Campaign)
        methods.clickElementByXPath(locators.select_Campaign_value)
        methods.clickElementByXPath(locators.select_Campaign_value1)
        methods.clickElementByXPath(locators.select_Campaign_value2)
        methods.clickElementByXPath(locators.adpilot_editicon)
        methods.ClearAndTypeWithXpath(locators.adpilot_edit_searchbar, new_campaign)
        methods.clickElementByXPath(locators.Campaign)
        methods.clickElementByXPath(locators.adpilot_publish)
        methods.assertElementContainsText(locators.notification_popup, "SuccessRule Successfully Created!")
        cy.wait(Timeout.sm)
        methods.clickElementByXPath(locators.adpilot_arrow_left)
        cy.wait(Timeout.sm)
        cy.xpath(`//h4[text()="${new_campaign}"]`, { timeout: extraTimeOut }).click({ force: true })
        cy.wait(Timeout.sm)
        methods.clickElementByXPath(locators.active_Toggle1)
        methods.clickElementByXPath(locators.pause)
        methods.assertElementContainsText(locators.notification_popup, "SuccessRule Successfully Updated!")
        methods.clickElementByXPath(locators.adpilot_arrow_left)
        cy.wait(Timeout.xs)
        cy.xpath(`//h4[text()="${new_campaign}"]//following::span[1]`, { timeout: extraTimeOut }).should('contain', "Paused");
        cy.wait(Timeout.xs)
    })

    it('To verify whether the publish functionality is working has expected', () => {

        cy.wait(Timeout.md)
        methods.scrollWithXpath(locators.Account_Pagetitle)
        methods.assertElementContainsTextxpath(locators.Account_Pagetitle, 'All Accounts')
        methods.VisibilityofElement(locators.account_pageloaded)
        cy.wait(Timeout.sm)
        methods.clickElementByXPath(locators.Adpilot)
        methods.VisibilityofElementXpath(locators.SmartReach)
        cy.wait(Timeout.sm)
        cy.xpath(`//h4[text()="${new_campaign}"]`, { timeout: extraTimeOut }).click({ force: true })
        cy.wait(Timeout.xs)
        methods.clickElementByXPath(locators.New_Campaign_Pause)
        cy.wait(Timeout.xs)
        methods.clickElementByXPath(locators.confirm_publish)
        methods.assertElementContainsText(locators.notification_popup, "SuccessRule Successfully Updated!")
        methods.clickElementByXPath(locators.adpilot_arrow_left)
        cy.xpath(`//h4[text()="${new_campaign}"]//following::span[1]`, { timeout: extraTimeOut }).should('contain', "Active");
        cy.wait(Timeout.sm)
        cy.xpath(`//h4[text()="${new_campaign}"]`, { timeout: extraTimeOut }).click({ force: true })
        cy.wait(Timeout.sm)
        methods.clickElementByXPath(locators.Campaign_MoreOption)
        methods.clickElementByXPath(locators.delete)
        cy.wait(Timeout.xs)
        methods.clickElementByXPath(locators.Ok)
        methods.assertElementContainsText(locators.notification_popup, "SuccessRule Successfully Deleted!")
    })
})