import Login1 from '../PageObjects/Login1';
import { deviceViewport, extraTimeOut, Timeout } from '../Utils.js';
import dayjs from 'dayjs';
import methods from '../../support/Common_Method.js';
import locators from '../../support/Locators.js';

describe('Profile Report Regression', () => {

    beforeEach(() => {

        cy.viewport(deviceViewport);

        cy.on('uncaught:exception', (err, runnable) => {
            return false;
        });

        //login before run test
        Login1();

    })

    it('TC_RE_01 - Profile Report - New Report', () => {

        cy.wait(Timeout.md)
        methods.assertElementContainsTextxpath(locators.Account_Pagetitle, 'All Accounts')
        methods.Mouseover(locators.report_dropdown)
        methods.clickElementByXPath(locators.Dashboards)
        cy.wait(Timeout.sm)
        methods.Mouseover(locators.report_dropdown)
        methods.clickElementByXPath(locators.Dashboards)
        methods.VisibilityofElement(locators.Dashboards_Title)
        methods.clickElement(locators.New_Report_CSS)
        methods.clickElementByXPath(locators.Profile_Report)
        methods.VisibilityofElementXpath(locators.PROFILESTOANALYSE)
    })

    it('TC_RE_02 - Profile Report - Add event', () => {

        cy.wait(Timeout.md)
        methods.assertElementContainsTextxpath(locators.Account_Pagetitle, 'All Accounts')
        methods.Mouseover(locators.report_dropdown)
        methods.clickElementByXPath(locators.Dashboards)
        cy.wait(Timeout.sm)
        methods.Mouseover(locators.report_dropdown)
        methods.clickElementByXPath(locators.Dashboards)
        methods.VisibilityofElement(locators.Dashboards_Title)
        methods.clickElement(locators.New_Report_CSS)
        methods.clickElementByXPath(locators.Profile_Report)
        methods.VisibilityofElementXpath(locators.PROFILESTOANALYSE)
        methods.clickElementByXPath(locators.Add_New_1)
        methods.clickElement(locators.Website_Visitors)

    })

    it('TC_RE_03 - Profile Report - Add multiple event', () => {

        cy.wait(Timeout.md)
        methods.assertElementContainsTextxpath(locators.Account_Pagetitle, 'All Accounts')
        methods.Mouseover(locators.report_dropdown)
        methods.clickElementByXPath(locators.Dashboards)
        cy.wait(Timeout.sm)
        methods.Mouseover(locators.report_dropdown)
        methods.clickElementByXPath(locators.Dashboards)
        methods.VisibilityofElement(locators.Dashboards_Title)
        methods.clickElement(locators.New_Report_CSS)
        methods.clickElementByXPath(locators.Profile_Report)
        methods.VisibilityofElementXpath(locators.PROFILESTOANALYSE)
        methods.clickElementByXPath(locators.Add_New_1)
        methods.clickElement(locators.Website_Visitors)
        methods.clickElementByXPath(locators.Add_New_1)
        methods.clickElement(locators.Hubspot_Contacts)
    })

    it('TC_RE_04 - Profile Report - Add local filter', () => {

        cy.wait(Timeout.md)
        methods.assertElementContainsTextxpath(locators.Account_Pagetitle, 'All Accounts')
        methods.Mouseover(locators.report_dropdown)
        methods.clickElementByXPath(locators.Dashboards)
        cy.wait(Timeout.sm)
        methods.Mouseover(locators.report_dropdown)
        methods.clickElementByXPath(locators.Dashboards)
        methods.VisibilityofElement(locators.Dashboards_Title)
        methods.clickElement(locators.New_Report_CSS)
        methods.clickElementByXPath(locators.Profile_Report)
        methods.VisibilityofElementXpath(locators.PROFILESTOANALYSE)
        methods.clickElementByXPath(locators.Add_New_1)
        methods.clickElement(locators.Website_Visitors)
        methods.MouseoverAndClick(locators.Filte_this_Profile)
        methods.clickElement0(locators.others, 0)
        methods.clickElementByXPath(locators.account_filter)
        methods.clickElementByXPath(locators.not_Set)
        methods.clickElementByXPath(locators.Apply1)
    })

    it('TC_RE_05 - Profile Report - Checking global filter ', () => {

        cy.wait(Timeout.md)
        methods.assertElementContainsTextxpath(locators.Account_Pagetitle, 'All Accounts')
        methods.Mouseover(locators.report_dropdown)
        methods.clickElementByXPath(locators.Dashboards)
        cy.wait(Timeout.sm)
        methods.Mouseover(locators.report_dropdown)
        methods.clickElementByXPath(locators.Dashboards)
        methods.VisibilityofElement(locators.Dashboards_Title)
        methods.clickElement(locators.New_Report_CSS)
        methods.clickElementByXPath(locators.Profile_Report)
        methods.VisibilityofElementXpath(locators.PROFILESTOANALYSE)
        methods.clickElementByXPath(locators.Add_New_1)
        methods.clickElement(locators.Website_Visitors)
        methods.VisibilityofElementXpath(locators.Add_New_FilterBy)
    })

    it('TC_RE_06 - Profile Report - Add multiple local filter ', () => {

        cy.wait(Timeout.md)
        methods.assertElementContainsTextxpath(locators.Account_Pagetitle, 'All Accounts')
        methods.Mouseover(locators.report_dropdown)
        methods.clickElementByXPath(locators.Dashboards)
        cy.wait(Timeout.sm)
        methods.Mouseover(locators.report_dropdown)
        methods.clickElementByXPath(locators.Dashboards)
        methods.VisibilityofElement(locators.Dashboards_Title)
        methods.clickElement(locators.New_Report_CSS)
        methods.clickElementByXPath(locators.Profile_Report)
        methods.VisibilityofElementXpath(locators.PROFILESTOANALYSE)
        methods.clickElementByXPath(locators.Add_New_1)
        methods.clickElement(locators.Website_Visitors)
        methods.MouseoverAndClick(locators.Filte_this_Profile)
        methods.clickElement0(locators.others, 0)
        methods.clickElementByXPath(locators.account_filter)
        methods.clickElementByXPath(locators.not_Set)
        methods.clickElementByXPath(locators.Apply1)
        methods.MouseoverAndClick(locators.Filte_this_Profile)
        methods.clickElement0(locators.User_identification, 0)
        methods.clickElementByXPath(locators.pageview_option1)
        methods.clickElementByXPath(locators.false)
        methods.clickElementByXPath(locators.Apply1)

    })

    it('TC_RE_07 - Profile Report - Delete event ', () => {

        cy.wait(Timeout.md)
        methods.assertElementContainsTextxpath(locators.Account_Pagetitle, 'All Accounts')
        methods.Mouseover(locators.report_dropdown)
        methods.clickElementByXPath(locators.Dashboards)
        cy.wait(Timeout.sm)
        methods.Mouseover(locators.report_dropdown)
        methods.clickElementByXPath(locators.Dashboards)
        methods.VisibilityofElement(locators.Dashboards_Title)
        methods.clickElement(locators.New_Report_CSS)
        methods.clickElementByXPath(locators.Profile_Report)
        methods.VisibilityofElementXpath(locators.PROFILESTOANALYSE)
        methods.clickElementByXPath(locators.Add_New_1)
        methods.clickElement(locators.Website_Visitors)
        methods.clickElementByXPath(locators.Add_New_1)
        methods.clickElement(locators.Hubspot_Contacts)
        methods.MouseoverAndClick(locators.Delete_this_Profile)
    })

    it('TC_RE_08 - Profile Report - Add global filter ', () => {

        cy.wait(Timeout.md)
        methods.assertElementContainsTextxpath(locators.Account_Pagetitle, 'All Accounts')
        methods.Mouseover(locators.report_dropdown)
        methods.clickElementByXPath(locators.Dashboards)
        cy.wait(Timeout.sm)
        methods.Mouseover(locators.report_dropdown)
        methods.clickElementByXPath(locators.Dashboards)
        methods.VisibilityofElement(locators.Dashboards_Title)
        methods.clickElement(locators.New_Report_CSS)
        methods.clickElementByXPath(locators.Profile_Report)
        methods.VisibilityofElementXpath(locators.PROFILESTOANALYSE)
        methods.clickElementByXPath(locators.Add_New_1)
        methods.clickElement(locators.Website_Visitors)
        methods.clickElementByXPath(locators.Add_New_FilterBy)
        methods.clickElement0(locators.Traffic_source, 0)
        methods.clickElementByXPath(locators.pageview_option1)
        methods.clickElementByXPath(locators.false)
        methods.clickElementByXPath(locators.Apply1)
    })

    it('TC_RE_09 - Profile Report - Add multiple global filter ', () => {

        cy.wait(Timeout.md)
        methods.assertElementContainsTextxpath(locators.Account_Pagetitle, 'All Accounts')
        methods.Mouseover(locators.report_dropdown)
        methods.clickElementByXPath(locators.Dashboards)
        cy.wait(Timeout.sm)
        methods.Mouseover(locators.report_dropdown)
        methods.clickElementByXPath(locators.Dashboards)
        methods.VisibilityofElement(locators.Dashboards_Title)
        methods.clickElement(locators.New_Report_CSS)
        methods.clickElementByXPath(locators.Profile_Report)
        methods.VisibilityofElementXpath(locators.PROFILESTOANALYSE)
        methods.clickElementByXPath(locators.Add_New_1)
        methods.clickElement(locators.Website_Visitors)
        methods.clickElementByXPath(locators.Add_New_FilterBy)
        methods.clickElement0(locators.Traffic_source, 0)
        methods.clickElementByXPath(locators.pageview_option1)
        methods.clickElementByXPath(locators.false)
        methods.clickElementByXPath(locators.Apply1)
        methods.clickElementByXPath(locators.Add_New_FilterBy)
        methods.clickElement0(locators.User_identification, 0)
        methods.clickElementByXPath(locators.pageview_option1)
        methods.clickElementByXPath(locators.false)
        methods.clickElementByXPath(locators.Apply1)

    })

    it('TC_RE_10 - Profile Report - Use + button ', () => {

        cy.wait(Timeout.md)
        methods.assertElementContainsTextxpath(locators.Account_Pagetitle, 'All Accounts')
        methods.Mouseover(locators.report_dropdown)
        methods.clickElementByXPath(locators.Dashboards)
        cy.wait(Timeout.sm)
        methods.Mouseover(locators.report_dropdown)
        methods.clickElementByXPath(locators.Dashboards)
        methods.VisibilityofElement(locators.Dashboards_Title)
        methods.clickElement(locators.New_Report_CSS)
        methods.clickElementByXPath(locators.Profile_Report)
        methods.VisibilityofElementXpath(locators.PROFILESTOANALYSE)
        methods.clickElementByXPath(locators.Add_New_1)
        methods.clickElement(locators.Website_Visitors)
        methods.MouseoverAndClick(locators.Filte_this_Profile)
        methods.clickElement0(locators.others, 0)
        methods.clickElementByXPath(locators.account_filter)
        cy.wait(Timeout.sm)
        methods.clickElementByXPath(locators.account_filter)
        methods.clickElementByXPath(locators.Apply1)
        methods.clickElementByXPath(locators.Add_Plus_button)
        methods.clickElement0(locators.others, 0)
        methods.clickElementByXPath(locators.account_filter)
        cy.wait(Timeout.sm)
        methods.clickElementByXPath(locators.account_filter)
        methods.clickElementByXPath(locators.Apply1)
        methods.assertElementContainsTextxpath(locators.or_1, 'or')
    })

    it('TC_RE_11 - Profile Report - Add breakdown ', () => {

        cy.wait(Timeout.md)
        methods.assertElementContainsTextxpath(locators.Account_Pagetitle, 'All Accounts')
        methods.Mouseover(locators.report_dropdown)
        methods.clickElementByXPath(locators.Dashboards)
        cy.wait(Timeout.sm)
        methods.Mouseover(locators.report_dropdown)
        methods.clickElementByXPath(locators.Dashboards)
        methods.VisibilityofElement(locators.Dashboards_Title)
        methods.clickElement(locators.New_Report_CSS)
        methods.clickElementByXPath(locators.Profile_Report)
        methods.VisibilityofElementXpath(locators.PROFILESTOANALYSE)
        methods.clickElementByXPath(locators.Add_New_1)
        methods.clickElement(locators.Website_Visitors)
        methods.clickElementByXPath(locators.Add_New_FilterBy)
        methods.clickElement0(locators.Traffic_source, 0)
        methods.clickElementByXPath(locators.pageview_option1)
        methods.clickElementByXPath(locators.false)
        methods.clickElementByXPath(locators.Apply1)
        methods.clickElementByXPath(locators.BreakDown_AddNew)
        methods.clickElement0(locators.others, 0)
        methods.clickElementByXPath(locators.Filter_option1)
        methods.clickElementByXPath(locators.BreakDown_AddNew)
        methods.clickElement0(locators.others, 0)
        methods.clickElementByXPath(locators.Filter_option2)

    })

    it('TC_RE_12 - Profile Report - Run analyse ', () => {

        cy.wait(Timeout.md)
        methods.assertElementContainsTextxpath(locators.Account_Pagetitle, 'All Accounts')
        methods.Mouseover(locators.report_dropdown)
        methods.clickElementByXPath(locators.Dashboards)
        cy.wait(Timeout.sm)
        methods.Mouseover(locators.report_dropdown)
        methods.clickElementByXPath(locators.Dashboards)
        methods.VisibilityofElement(locators.Dashboards_Title)
        methods.clickElement(locators.New_Report_CSS)
        methods.clickElementByXPath(locators.Profile_Report)
        methods.VisibilityofElementXpath(locators.PROFILESTOANALYSE)
        methods.clickElementByXPath(locators.Add_New_1)
        methods.clickElement(locators.Website_Visitors)
        methods.clickElementByXPath(locators.Add_New_FilterBy)
        methods.clickElement0(locators.Traffic_source, 0)
        methods.clickElementByXPath(locators.pageview_option1)
        methods.clickElementByXPath(locators.false)
        methods.clickElementByXPath(locators.Apply1)
        methods.clickElementByXPath(locators.BreakDown_AddNew)
        methods.clickElement0(locators.others, 0)
        methods.clickElementByXPath(locators.Filter_option1)
        methods.clickElementByXPath(locators.Run_Anal)
        methods.VisibilityofElement(locators.Profile_report_gen)
    })

    it('TC_RE_13 - Profile Report - Download csv ', () => {

        cy.wait(Timeout.md)
        methods.assertElementContainsTextxpath(locators.Account_Pagetitle, 'All Accounts')
        methods.Mouseover(locators.report_dropdown)
        methods.clickElementByXPath(locators.Dashboards)
        cy.wait(Timeout.sm)
        methods.Mouseover(locators.report_dropdown)
        methods.clickElementByXPath(locators.Dashboards)
        methods.VisibilityofElement(locators.Dashboards_Title)
        methods.clickElement(locators.New_Report_CSS)
        methods.clickElementByXPath(locators.Profile_Report)
        methods.VisibilityofElementXpath(locators.PROFILESTOANALYSE)
        methods.clickElementByXPath(locators.Add_New_1)
        methods.clickElement(locators.Website_Visitors)
        methods.clickElementByXPath(locators.Add_New_FilterBy)
        methods.clickElement0(locators.Traffic_source, 0)
        methods.clickElementByXPath(locators.pageview_option1)
        methods.clickElementByXPath(locators.false)
        methods.clickElementByXPath(locators.Apply1)
        methods.clickElementByXPath(locators.Run_Anal)
        methods.VisibilityofElement(locators.Profile_report_gen)
        methods.ScrollAndClickxpath(locators.CSVlink)
    })

    it('TC_RE_14 - Profile Report - Search ', () => {

        cy.wait(Timeout.md)
        methods.assertElementContainsTextxpath(locators.Account_Pagetitle, 'All Accounts')
        methods.Mouseover(locators.report_dropdown)
        methods.clickElementByXPath(locators.Dashboards)
        cy.wait(Timeout.sm)
        methods.Mouseover(locators.report_dropdown)
        methods.clickElementByXPath(locators.Dashboards)
        methods.VisibilityofElement(locators.Dashboards_Title)
        methods.clickElement(locators.New_Report_CSS)
        methods.clickElementByXPath(locators.Profile_Report)
        methods.VisibilityofElementXpath(locators.PROFILESTOANALYSE)
        methods.clickElementByXPath(locators.Add_New_1)
        methods.clickElement(locators.Website_Visitors)
        methods.clickElementByXPath(locators.BreakDown_AddNew)
        methods.typeElement(locators.select_property, "compa")
        methods.clickElement0(locators.Country_Breakdown, 0)
        methods.clickElementByXPath(locators.Run_Anal)
        methods.VisibilityofElement(locators.Profile_report_gen)
        methods.scrollWithXpath(locators.Break_up)
        methods.clickElementByXPath(locators.Breakup_Search)
        methods.typeElement(locators.search_1, 'In')
        methods.assertElementContainsTextxpath(locators.Country_Search_result, 'India')
    })

    it('TC_RE_15 - Profile Report - Save ', () => {

        const nowTime = dayjs().format('H:m:s');
        const testName = `Demo_${nowTime}`;

        cy.wait(Timeout.md)
        methods.assertElementContainsTextxpath(locators.Account_Pagetitle, 'All Accounts')
        methods.Mouseover(locators.report_dropdown)
        methods.clickElementByXPath(locators.Dashboards)
        cy.wait(Timeout.sm)
        methods.Mouseover(locators.report_dropdown)
        methods.clickElementByXPath(locators.Dashboards)
        methods.VisibilityofElement(locators.Dashboards_Title)
        methods.clickElementByXPath(locators.Drafts)
        methods.clickElement(locators.New_Report_CSS)
        methods.clickElementByXPath(locators.Profile_Report)
        methods.VisibilityofElementXpath(locators.PROFILESTOANALYSE)
        methods.clickElementByXPath(locators.Add_New_1)
        methods.clickElement(locators.Website_Visitors)
        methods.clickElementByXPath(locators.BreakDown_AddNew)
        methods.clickElement0(locators.others, 0)
        methods.clickElementByXPath(locators.Filter_option1)
        methods.clickElementByXPath(locators.Run_Anal)
        methods.VisibilityofElement(locators.Attri_pageloaded)
        methods.clickElementByXPath(locators.Save_1)
        methods.typeElement(locators.Report_Name, testName)
        methods.typeElement(locators.Description_OP, 'Testing Report')
        methods.clickElementByXPath(locators.save1)
        methods.GetText(locators.notification_popup, "Report Saved Successfully")
        cy.wait(Timeout.sm)
        cy.xpath(`//h4[text()="${testName}"]//following::button[1]`,{ timeout: extraTimeOut }).trigger('mouseover', { force: true });
        methods.clickElementByXPath(locators.Delete_Report)
        cy.wait(Timeout.xs)
        methods.clickElementByXPath(locators.confirm_1)
        cy.wait(Timeout.xs)
    })

    it('TC_RE_16 - Profile Report - report to the dashboard ', () => {

        const nowTime = dayjs().format('H:m:s');
        const testName = `Demo_${nowTime}`;

        cy.wait(Timeout.md)
        methods.assertElementContainsTextxpath(locators.Account_Pagetitle, 'All Accounts')
        methods.Mouseover(locators.report_dropdown)
        methods.clickElementByXPath(locators.Dashboards)
        cy.wait(Timeout.sm)
        methods.Mouseover(locators.report_dropdown)
        methods.clickElementByXPath(locators.Dashboards)
        methods.VisibilityofElement(locators.Dashboards_Title)
        methods.clickElementByXPath(locators.Drafts)
        methods.VisibilityofElement(locators.Table_Body_1)
        methods.clickElement(locators.New_Report_CSS)
        methods.clickElementByXPath(locators.Profile_Report)
        methods.VisibilityofElementXpath(locators.PROFILESTOANALYSE)
        methods.clickElementByXPath(locators.Add_New_1)
        methods.clickElement(locators.Website_Visitors)
        methods.clickElementByXPath(locators.BreakDown_AddNew)
        methods.clickElement0(locators.others, 0)
        methods.clickElementByXPath(locators.Filter_option1)
        methods.clickElementByXPath(locators.Run_Anal)
        methods.VisibilityofElement(locators.Attri_pageloaded)
        methods.clickElementByXPath(locators.Save_1)
        methods.typeElement(locators.Report_Name, testName)
        methods.typeElement(locators.Description_OP, 'Testing Report')
        methods.clickElementByXPath(locators.save1)
        cy.wait(Timeout.sm)
        cy.xpath(`//h4[text()='${testName}']`, {}).click({ force: true })
        cy.wait(Timeout.sm)
        methods.MouseoverWithXpath(locators.Profile_Report_option)
        methods.clickElementByXPath(locators.Add_to_Dashboard)
        cy.wait(Timeout.sm)
        methods.clickElementByXPath(locators.Please_Select)
        methods.typeElementByXPath(locators.Please_Select, 'aut')
        cy.wait(Timeout.sm)
        methods.clickElement(locators.Automation_1)
        methods.clickElementByXPath(locators.Add_to_Dashboard_title)
        methods.clickElementByXPath(locators.Save_2)
        methods.VisibilityofElement(locators.notification_popup)
        methods.VisibilityofElement(locators.Attri_pageloaded)
        methods.clickElementByXPath(locators.Closed)
        cy.wait(Timeout.xs)
        methods.typeElement(locators.Search_dashboard, 'Auto')
        methods.clickElementByXPath(locators.Automate)
        methods.clickElementByXPath(locators.Automation_Delete)
        methods.clickElementByXPath(locators.Delete_Widget)
        cy.wait(Timeout.xs)
        methods.clickElementByXPath(locators.confirm_1)
        cy.wait(Timeout.sm)
        methods.clickElementByXPath(locators.Drafts)
        methods.VisibilityofElement(locators.Table_Body_1)
        cy.xpath(`//h4[text()="${testName}"]//following::button[1]`,{ timeout: extraTimeOut }).trigger('mouseover', { force: true });
        methods.clickElementByXPath(locators.Delete_Report)
        cy.wait(Timeout.xs)
        methods.clickElementByXPath(locators.confirm_1)
        cy.wait(Timeout.xs)

    })

})
