import Login3 from '../PageObjects/Login3';
import { deviceViewport, extraTimeOut } from '../Utils';
import dayjs from 'dayjs';
import methods from '../../support/Common_Method.js';
import locators from '../../support/Locators.js';

describe('Profile Report Login', () => {

    beforeEach(() => {

        cy.viewport(deviceViewport);

        cy.on('uncaught:exception', (err, runnable) => {
            return false;
        });

        //login before run test
        Login3();

    })

    it('TC_RE_01 - Profile Report - New Report', () => {

        cy.wait(5000)
        methods.assertElementContainsText(locators.Account_Pagetitle,'All Accounts',extraTimeOut)
        methods.Mouseover(locators.report_dropdown)
        methods.clickElementByXPath(locators.Dashboards)
        cy.wait(8000)
        methods.VisibilityofElement(locators.Dashboards_Title,extraTimeOut)
        methods.clickElement(locators.New_Report_CSS)
        methods.clickElementByXPath(locators.Profile_Report)
    })

    it('TC_RE_02 - Profile Report - Add event', () => {

        cy.wait(5000)
        methods.assertElementContainsText(locators.Account_Pagetitle,'All Accounts',extraTimeOut)
        methods.Mouseover(locators.report_dropdown)
        methods.clickElementByXPath(locators.Dashboards)
        cy.wait(8000)
        methods.VisibilityofElement(locators.Dashboards_Title,extraTimeOut)
        methods.clickElement(locators.New_Report_CSS)
        methods.clickElementByXPath(locators.Profile_Report)
        cy.wait(2000)
        methods.clickElementByXPath(locators.Add_New_1,extraTimeOut)
        methods.clickElement(locators.Website_Visitors)

    })

    it('TC_RE_03 - Profile Report - Add multiple event', () => {

        cy.wait(5000)
        methods.assertElementContainsText(locators.Account_Pagetitle,'All Accounts',extraTimeOut)
        methods.Mouseover(locators.report_dropdown)
        methods.clickElementByXPath(locators.Dashboards)
        cy.wait(8000)
        methods.VisibilityofElement(locators.Dashboards_Title,extraTimeOut)
        methods.clickElement(locators.New_Report_CSS)
        methods.clickElementByXPath(locators.Profile_Report)
        cy.wait(2000)
        methods.clickElementByXPath(locators.Add_New_1,extraTimeOut)
        methods.clickElement(locators.Website_Visitors)
        methods.clickElementByXPath(locators.Add_New_1,extraTimeOut)
        methods.clickElement(locators.Hubspot_Contacts)
    })

    it('TC_RE_04 - Profile Report - Add local filter', () => {

        cy.wait(5000)
        methods.assertElementContainsText(locators.Account_Pagetitle,'All Accounts',extraTimeOut)
        methods.Mouseover(locators.report_dropdown)
        methods.clickElementByXPath(locators.Dashboards)
        cy.wait(8000)
        methods.VisibilityofElement(locators.Dashboards_Title,extraTimeOut)
        methods.clickElement(locators.New_Report_CSS)
        methods.clickElementByXPath(locators.Profile_Report)
        cy.wait(2000)
        methods.clickElementByXPath(locators.Add_New_1,extraTimeOut)
        methods.clickElement(locators.Website_Visitors)
        methods.MouseoverAndClick(locators.Filte_this_Profile)
        methods.clickElement0(locators.others,0)
        methods.clickElementByXPath(locators.pageview_option1,extraTimeOut)
        cy.wait(1000)
        methods.clickElementByXPath(locators.pageview_option1,extraTimeOut)
        methods.clickElementByXPath(locators.Apply1,extraTimeOut)
        methods.clickElementByXPath(locators.Equals_text)
        methods.VisibilityofElement(locators.channel_dropdown)
        methods.clickElement(locators.equals_1)
    })

    it('TC_RE_05 - Profile Report - Checking global filter ', () => {

        cy.wait(5000)
        methods.assertElementContainsText(locators.Account_Pagetitle,'All Accounts',extraTimeOut)
        methods.Mouseover(locators.report_dropdown)
        methods.clickElementByXPath(locators.Dashboards)
        cy.wait(8000)
        methods.VisibilityofElement(locators.Dashboards_Title,extraTimeOut)
        methods.clickElement(locators.New_Report_CSS)
        methods.clickElementByXPath(locators.Profile_Report)
        cy.wait(2000)
        methods.clickElementByXPath(locators.Add_New_1,extraTimeOut)
        methods.clickElement(locators.Website_Visitors)
        methods.VisibilityofElementXpath(locators.Add_New_FilterBy)    
    })

    it('TC_RE_06 - Profile Report - Add multiple local filter ', () => {

        cy.wait(5000)
        methods.assertElementContainsText(locators.Account_Pagetitle,'All Accounts',extraTimeOut)
        methods.Mouseover(locators.report_dropdown)
        methods.clickElementByXPath(locators.Dashboards)
        cy.wait(8000)
        methods.VisibilityofElement(locators.Dashboards_Title,extraTimeOut)
        methods.clickElement(locators.New_Report_CSS)
        methods.clickElementByXPath(locators.Profile_Report)
        cy.wait(2000)
        methods.clickElementByXPath(locators.Add_New_1,extraTimeOut)
        methods.clickElement(locators.Website_Visitors)
        methods.MouseoverAndClick(locators.Filte_this_Profile)
        methods.clickElement0(locators.others,0)
        methods.clickElementByXPath(locators.pageview_option1,extraTimeOut)
        cy.wait(1000)
        methods.clickElementByXPath(locators.pageview_option1,extraTimeOut)
        methods.clickElementByXPath(locators.Apply1,extraTimeOut)
        
        methods.MouseoverAndClick(locators.Filte_this_Profile)
        cy.wait(2000)
        methods.clickElement0(locators.User_identification,0)
        methods.clickElementByXPath(locators.pageview_option1,extraTimeOut)
        methods.clickElementByXPath(locators.false)
        methods.clickElementByXPath(locators.Apply1)

    })

    it('TC_RE_07 - Profile Report - Delete event ', () => {

        cy.wait(5000)
        methods.assertElementContainsText(locators.Account_Pagetitle,'All Accounts',extraTimeOut)
        methods.Mouseover(locators.report_dropdown)
        methods.clickElementByXPath(locators.Dashboards)
        cy.wait(8000)
        methods.VisibilityofElement(locators.Dashboards_Title,extraTimeOut)
        methods.clickElement(locators.New_Report_CSS)
        methods.clickElementByXPath(locators.Profile_Report)
        cy.wait(2000)
        methods.clickElementByXPath(locators.Add_New_1,extraTimeOut)
        methods.clickElement(locators.Website_Visitors)
        methods.clickElementByXPath(locators.Add_New_1,extraTimeOut)
        methods.clickElement(locators.Hubspot_Contacts)
        methods.MouseoverAndClick(locators.Delete_this_Profile)
    })

    it('TC_RE_08 - Profile Report - Add global filter ', () => {

        cy.wait(5000)
        methods.assertElementContainsText(locators.Account_Pagetitle,'All Accounts',extraTimeOut)
        methods.Mouseover(locators.report_dropdown)
        methods.clickElementByXPath(locators.Dashboards)
        cy.wait(8000)
        methods.VisibilityofElement(locators.Dashboards_Title,extraTimeOut)
        methods.clickElement(locators.New_Report_CSS)
        methods.clickElementByXPath(locators.Profile_Report)
        cy.wait(2000)
        methods.clickElementByXPath(locators.Add_New_1,extraTimeOut)
        methods.clickElement(locators.Website_Visitors)
        methods.clickElementByXPath(locators.Add_New_FilterBy)
        methods.clickElement0(locators.Traffic_source,0)
        methods.clickElementByXPath(locators.pageview_option1,extraTimeOut)
        methods.clickElementByXPath(locators.false)
        methods.clickElementByXPath(locators.Apply1)
    })

    it('TC_RE_09 - Profile Report - Add multiple global filter ', () => {

        cy.wait(5000)
        methods.assertElementContainsText(locators.Account_Pagetitle,'All Accounts',extraTimeOut)
        methods.Mouseover(locators.report_dropdown)
        methods.clickElementByXPath(locators.Dashboards)
        cy.wait(8000)
        methods.VisibilityofElement(locators.Dashboards_Title,extraTimeOut)
        methods.clickElement(locators.New_Report_CSS)
        methods.clickElementByXPath(locators.Profile_Report)
        cy.wait(2000)
        methods.clickElementByXPath(locators.Add_New_1,extraTimeOut)
        methods.clickElement(locators.Website_Visitors)
        methods.clickElementByXPath(locators.Add_New_FilterBy)
        methods.clickElement0(locators.Traffic_source,0)
        methods.clickElementByXPath(locators.pageview_option1,extraTimeOut)
        methods.clickElementByXPath(locators.false)
        methods.clickElementByXPath(locators.Apply1)
        methods.clickElementByXPath(locators.Add_New_FilterBy)
        cy.wait(2000)
        methods.clickElement0(locators.User_identification,0)
        methods.clickElementByXPath(locators.pageview_option1,extraTimeOut)
        cy.wait(1000)
        methods.clickElementByXPath(locators.false)
        methods.clickElementByXPath(locators.Apply1)

    })

    it('TC_RE_10 - Profile Report - Use + button ', () => {

        cy.wait(5000)
        methods.assertElementContainsText(locators.Account_Pagetitle,'All Accounts',extraTimeOut)
        methods.Mouseover(locators.report_dropdown)
        methods.clickElementByXPath(locators.Dashboards)
        cy.wait(8000)
        methods.VisibilityofElement(locators.Dashboards_Title,extraTimeOut)
        methods.clickElement(locators.New_Report_CSS)
        methods.clickElementByXPath(locators.Profile_Report)
        cy.wait(2000)
        methods.clickElementByXPath(locators.Add_New_1,extraTimeOut)
        methods.clickElement(locators.Website_Visitors)
        methods.MouseoverAndClick(locators.Filte_this_Profile)
        methods.clickElement0(locators.others,0)
        methods.clickElementByXPath(locators.pageview_option1,extraTimeOut)
        cy.wait(1000)
        methods.clickElementByXPath(locators.pageview_option1,extraTimeOut)
        methods.clickElementByXPath(locators.Apply1,extraTimeOut)
        methods.clickElementByXPath(locators.Add_Plus_button)
        cy.wait(2000)
        methods.clickElement0(locators.others,0)
        methods.clickElementByXPath(locators.pageview_option1,extraTimeOut)
        cy.wait(1000)
        methods.clickElementByXPath(locators.pageview_option1,extraTimeOut)
        methods.clickElementByXPath(locators.Apply1,extraTimeOut)
        methods.assertElementContainsTextxpath(locators.or_1,'or')
    })

    it('TC_RE_11 - Profile Report - Add breakdown ', () => {

        cy.wait(5000)
        methods.assertElementContainsText(locators.Account_Pagetitle,'All Accounts',extraTimeOut)
        methods.Mouseover(locators.report_dropdown)
        methods.clickElementByXPath(locators.Dashboards)
        cy.wait(8000)
        methods.VisibilityofElement(locators.Dashboards_Title,extraTimeOut)
        methods.clickElement(locators.New_Report_CSS)
        methods.clickElementByXPath(locators.Profile_Report)
        cy.wait(2000)
        methods.clickElementByXPath(locators.Add_New_1,extraTimeOut)
        methods.clickElement(locators.Website_Visitors)
        methods.clickElementByXPath(locators.Add_New_FilterBy)
        methods.clickElement0(locators.Traffic_source,0)
        methods.clickElementByXPath(locators.pageview_option1,extraTimeOut)
        methods.clickElementByXPath(locators.false)
        methods.clickElementByXPath(locators.Apply1)
        methods.clickElementByXPath(locators.BreakDown_AddNew)
        methods.clickElement0(locators.others,0)
        methods.clickElementByXPath(locators.Filter_option1,extraTimeOut)
        methods.clickElementByXPath(locators.BreakDown_AddNew)
        methods.clickElement0(locators.others,0)
        methods.clickElementByXPath(locators.Filter_option2,extraTimeOut)

    })

    it('TC_RE_12 - Profile Report - Run analyse ', () => {

        cy.wait(5000)
        methods.assertElementContainsText(locators.Account_Pagetitle,'All Accounts',extraTimeOut)
        methods.Mouseover(locators.report_dropdown)
        methods.clickElementByXPath(locators.Dashboards)
        cy.wait(8000)
        methods.VisibilityofElement(locators.Dashboards_Title,extraTimeOut)
        methods.clickElement(locators.New_Report_CSS)
        methods.clickElementByXPath(locators.Profile_Report)
        cy.wait(2000)
        methods.clickElementByXPath(locators.Add_New_1,extraTimeOut)
        methods.clickElement(locators.Website_Visitors)
        methods.clickElementByXPath(locators.Add_New_FilterBy)
        methods.clickElement0(locators.Traffic_source,0)
        methods.clickElementByXPath(locators.pageview_option1,extraTimeOut)
        methods.clickElementByXPath(locators.false)
        methods.clickElementByXPath(locators.Apply1)
        methods.clickElementByXPath(locators.BreakDown_AddNew)
        methods.clickElement0(locators.others,0)
        methods.clickElementByXPath(locators.Filter_option1,extraTimeOut)
        methods.clickElementByXPath(locators.Run_Anal)
        methods.VisibilityofElement(locators.Profile_report_gen)
    })

    it('TC_RE_13 - Profile Report - Download csv ', () => {

        cy.wait(5000)
        methods.assertElementContainsText(locators.Account_Pagetitle,'All Accounts',extraTimeOut)
        methods.Mouseover(locators.report_dropdown)
        methods.clickElementByXPath(locators.Dashboards)
        cy.wait(8000)
        methods.VisibilityofElement(locators.Dashboards_Title,extraTimeOut)
        methods.clickElement(locators.New_Report_CSS)
        methods.clickElementByXPath(locators.Profile_Report)
        cy.wait(2000)
        methods.clickElementByXPath(locators.Add_New_1,extraTimeOut)
        methods.clickElement(locators.Website_Visitors)
        methods.clickElementByXPath(locators.Add_New_FilterBy)
        methods.clickElement0(locators.Traffic_source,0)
        methods.clickElementByXPath(locators.pageview_option1,extraTimeOut)
        methods.clickElementByXPath(locators.false)
        methods.clickElementByXPath(locators.Apply1)
        methods.clickElementByXPath(locators.Run_Anal)
        methods.VisibilityofElement(locators.Profile_report_gen)
        methods.clickElement(locators.CSVlink)       
    })

    it('TC_RE_14 - Profile Report - Search ', () => {

        cy.wait(5000)
        methods.assertElementContainsText(locators.Account_Pagetitle,'All Accounts',extraTimeOut)
        methods.Mouseover(locators.report_dropdown)
        methods.clickElementByXPath(locators.Dashboards)
        cy.wait(8000)
        methods.VisibilityofElement(locators.Dashboards_Title,extraTimeOut)
        methods.clickElement(locators.New_Report_CSS)
        methods.clickElementByXPath(locators.Profile_Report)
        cy.wait(2000)
        methods.clickElementByXPath(locators.Add_New_1,extraTimeOut)
        methods.clickElement(locators.Website_Visitors)
        methods.clickElementByXPath(locators.BreakDown_AddNew)
        methods.clickElement0(locators.others,0)
        methods.typeElement(locators.select_property,'cou')
        cy.wait(1000)
        methods.clickElement(locators.Country)
        methods.clickElementByXPath(locators.Run_Anal)
        methods.scrollWithXpath(locators.Break_up)
        methods.clickElementByXPath(locators.Breakup_Search)
        methods.typeElement(locators.search_1,'fra')
        methods.assertElementContainsTextxpath(locators.Country_Search_result,'FRANCE')       
    })

    it('TC_RE_15 - Profile Report - Save ', () => {

        const nowTime = dayjs().format('H:m:s');
        const testName = `Demo_${nowTime}`;

        cy.wait(5000)
        methods.assertElementContainsText(locators.Account_Pagetitle,'All Accounts',extraTimeOut)
        methods.Mouseover(locators.report_dropdown)
        methods.clickElementByXPath(locators.Dashboards)
        cy.wait(8000)
        methods.VisibilityofElement(locators.Dashboards_Title,extraTimeOut)
        methods.clickElement(locators.New_Report_CSS)
        methods.clickElementByXPath(locators.Profile_Report)
        cy.wait(2000)
        methods.clickElementByXPath(locators.Add_New_1,extraTimeOut)
        methods.clickElement(locators.Website_Visitors)
        methods.clickElementByXPath(locators.BreakDown_AddNew)
        methods.clickElement0(locators.others,0)
        methods.typeElement(locators.select_property,'cou')
        cy.wait(1000)
        methods.clickElement(locators.Country)
        methods.clickElementByXPath(locators.Run_Anal)
        methods.VisibilityofElement(locators.Attri_pageloaded,extraTimeOut)
        methods.clickElementByXPath(locators.Save_1)
        methods.typeElement(locators.Report_Name,testName)
        methods.typeElement(locators.Description_OP,'Testing Report')
        methods.clickElementByXPath(locators.save1)
        methods.VisibilityofElement(locators.notification_popup,extraTimeOut)
        methods.clickElementByXPath(locators.Closed)
        methods.clickElementByXPath(locators.Drafts)
        methods.MouseoverWithXpath(locators.Saved_report_option)
        methods.clickElementByXPath(locators.Delete_Report)
        methods.clickElementByXPath(locators.confirm_1)
        cy.wait(2000)
    })

    it('TC_RE_16 - Profile Report - report to the dashboard ', () => {

        const nowTime = dayjs().format('H:m:s');
        const testName = `Demo_${nowTime}`;

        cy.wait(5000)
        methods.assertElementContainsText(locators.Account_Pagetitle,'All Accounts',extraTimeOut)
        methods.Mouseover(locators.report_dropdown)
        methods.clickElementByXPath(locators.Dashboards)
        cy.wait(8000)
        methods.VisibilityofElement(locators.Dashboards_Title,extraTimeOut)
        methods.clickElement(locators.New_Report_CSS)
        methods.clickElementByXPath(locators.Profile_Report)
        cy.wait(2000)
        methods.clickElementByXPath(locators.Add_New_1,extraTimeOut)
        methods.clickElement(locators.Website_Visitors)
        methods.clickElementByXPath(locators.BreakDown_AddNew)
        methods.clickElement0(locators.others,0)
        methods.typeElement(locators.select_property,'cou')
        cy.wait(1000)
        methods.clickElement(locators.Country)
        methods.clickElementByXPath(locators.Run_Anal) 
        methods.VisibilityofElement(locators.Attri_pageloaded,extraTimeOut)
        methods.clickElementByXPath(locators.Save_1)
        methods.typeElement(locators.Report_Name,testName)
        methods.typeElement(locators.Description_OP,'Testing Report')
        methods.clickElementByXPath(locators.save1)
        cy.wait(2000)
        methods.MouseoverWithXpath(locators.Profile_Report_option)
        methods.clickElementByXPath(locators.Add_to_Dashboard)
        methods.clickElementByXPath(locators.Please_Select)
        methods.typeElementByXPath(locators.Please_Select,'aut')
        methods.clickElement(locators.Automation_1)
        methods.clickElementByXPath(locators.Add_to_Dashboard_title)
        methods.clickElementByXPath(locators.Save_2)
        methods.VisibilityofElement(locators.notification_popup,extraTimeOut)
        methods.clickElementByXPath(locators.Closed)
        methods.clickElementByXPath(locators.Automation_Folder)
        methods.clickElementByXPath(locators.Automate)
        cy.wait(2000)
        methods.MouseoverWithXpath(locators.Automation_Delete)
        methods.clickElementByXPath(locators.Delete_Widget)
        methods.clickElementByXPath(locators.confirm_1)
        cy.wait(3000)
        methods.clickElementByXPath(locators.Drafts)
        methods.MouseoverWithXpath(locators.Saved_report_option)
        methods.clickElementByXPath(locators.Delete_Report)
        methods.clickElementByXPath(locators.confirm_1)
        cy.wait(2000)

    })
    
})
