class locators {

    constructor() {

        this.Account_FirstValue = '//div[text()="Account Domain"]//following::tr[2]/td[1]';
        this.Account_value = '//div[text()="Open"]//following::div[1]';
        this.Account_value_Close = '//div[text()="Open"]//following::button[2]';
        this.Open_NewTab = '//div[text()="Account Domain"]//following::button[2]';
        this.account_dropdown = '#fa-at-link--accounts';
        this.account = '.ant-dropdown > .ant-dropdown-menu > li:nth-child(${item.index}) > span > a';
        this.Account_Pagetitle = '#fa-at-text--page-title';
        this.report_dropdown = '#fa-at-link--journeys';
        this.attributes = '//h4[text()="Attribution"]';
        this.configure = '#fa-at-dropdown--config';
        this.configure_dropdown = '.fa-at-overlay--config > ul > li:nth-child(${item.index}) > span > a';
        this.usermail = '#fa-at-dropdown--projects div.opacity-80';
        this.setting = '#fa-at-dropdown--settings';
        this.pricing_breadcrumb = '.ant-breadcrumb';
        this.billing = '.ant-breadcrumb span:nth-child(3) > span.ant-breadcrumb-link';
        this.Account_identification = '//h4[text()="Account identification"]';
        this.identi_table = '.ant-table-container';
        this.table_row1 = '.ant-table-tbody > :nth-child(1) > :nth-child(1)';
        this.table_row2 = '.ant-table-tbody > :nth-child(2) > :nth-child(1)';
        this.channel = '.gap-4 > :nth-child(1) > .ant-btn';
        this.channel_dropdown = '.fa-select-dropdown > .flex';
        this.Organic_Search = '[title="Organic Search"]';
        this.organic_table1 = '.ant-table-tbody > :nth-child(1) > :nth-child(2)';
        this.organic_table2 = '.ant-table-tbody > :nth-child(2) > :nth-child(2)';
        this.organic_table3 = '.ant-table-tbody > :nth-child(3) > :nth-child(2)';
        this.direct = '[title="Direct"]';
        this.paid_search = '[title="Paid Search"]';
        this.campaign = '.gap-4 > :nth-child(2) > div > .ant-btn';
        this.campaign_dropdown = '.fa-select-dropdown';
        this.TD_Search_Remarketing_Competitors = '[title="TD_Search_Remarketing_Competitors"]';
        this.Apply = '.fa-select--buttons > .ant-btn';
        this.TD_Search_US_Deanon_Competition = '[title="TD_Search_US_Deanon_Competition"]';
        this.page_view = '.gap-4 > :nth-child(3) > div > .ant-btn';
        this.pageview_dropdown = '.FaSelect_dropdown__select__1L5kx';
        this.pageview_option1 = '//input[@placeholder="Search"]//following::div[3]';
        this.pageview_option2 = '//input[@placeholder="Search"]//following::div[5]';
        this.pageview_option3 = '//input[@placeholder="Search"]//following::div[7]';
        this.pageview_option4 = '//input[@placeholder="Search"]//following::div[9]';
        this.pageview_option5 = '//input[@placeholder="Search"]//following::div[4]';
        this.pageview_option6 = '//input[@placeholder="Search"]//following::div[5]';
        this.Upgrade_validation = '.ant-modal-body';
        this.Filter_option2 = '//input[@placeholder="Select Property"]//following::div[4]';
        this.Filter_option1 = '//input[@placeholder="Select Property"]//following::div[3]';
        this.identi_table1 = '.ant-table-wrapper';
        this.calender = '//h4[text()="Channel"]//following::button[3]';
        this.select_date = '//div[@title="Today"]//following::div[3]';
        this.share = '.justify-between.align-middle > :nth-child(2)';
        this.share1 = '//span[text()="Share"]'
        this.email_field = '#share-modal-form_emails_0';
        this.done = '[type="submit"]';
        this.Continue = '//*[text()="Continue"]';
        this.notification_popup = '.ant-notification-notice';
        this.notification_popup1 = '.ant-notification-notice-message';
        this.notification_popup3 = '.ant-notification';
        this.clear = '.FaSelect_dropdown__clear_opt__263i6 > .ant-btn';
        this.search = '.DataTable_searchBar__1fGz4 > .justify-between > :nth-child(2) > :nth-child(1) > .ant-btn';
        this.search_field = '.DataTable_searchBar__1fGz4';
        this.Klenty_details = '.ant-table-row > :nth-child(1)';
        this.X_button = '.DataTable_searchBar__1fGz4 > .justify-between > :nth-child(2) > :nth-child(1) > .ant-btn';
        this.download = ':nth-child(2) > :nth-child(2) > .ant-btn';
        this.account_pageloaded = ':nth-child(2) > .ant-table-cell-fix-left';
        this.search_button = '.relative > .ant-btn';
        this.search_area = '//*[@placeholder="Search Accounts"]';
        this.download_button = '//h4[text()="All Accounts"]//following::button[4]';
        this.download_header = '.fai-text__size--h5';
        this.exportCSV = '.ant-btn-primary';
        this.filter = '.w-full > .ant-btn';
        this.filter_css = '.w-full > .ant-btn-text';
        this.Add_filter = '(//*[text()="Add filter"])[1]';
        this.select_Accountprop = '.FaSelect_hoveredOption__Cs1tw';
        this.Visited_Website = '[title="Visited Website"]';
        this.true = '[title="True"]';
        this.true1 = '[title="true"]';
        this.Add_event = '//*[text()="Add event"]';
        this.Event_performed = '.fa-select-dropdown > .flex-col > :nth-child(5)';
        this.select_option = '//input[@placeholder="Select Event"]//following::div[3]';
        this.Apply_Changes = '.flex > .ant-btn-primary > span';
        this.save_segment = '.w-full > .ant-btn-default';
        this.segment_name = '.flex > .ant-input';
        this.Save = '//*[text()="Save"]';
        this.Search_segment = '[placeholder="Search segment"]';
        this.Select_segment = '//h4[text()="Segments"]//following::div[2]';
        this.Threedots = '//h1[text()="filter(s)"]//following::button[4]';
        this.Threedots1 = '//h1[text()="filter(s)"]//following::button[3]';
        this.rename_segment = '.ant-popover-inner-content > :nth-child(1) > .flex-col > :nth-child(1)';
        this.Delect_segment = '//h1[text()="Delete Segment"]';
        this.confirm = '//*[text()="Confirm"]';
        this.Add_column_1 = '.inline-flex > :nth-child(3)';
        this.Table_properties = '.ant-popover-inner-content';
        this.company_name = '[data-id="Company name"]';
        this.Apply1 = '//span[text()="Apply"]';
        this.People = '//h4[text()="People"]';
        this.Search1 = '//*[@placeholder="Search Users"]';
        this.rowname = '.ant-table-row > .ant-table-cell-fix-left';
        this.Add_column = '.inline-flex > :nth-child(2)';
        this.table_property = '.ant-tabs';
        this.company_name1 = '[data-id="Company Country"] > .justify-between';
        this.row_validation = '.ant-table-cell-content > .flex';
        this.Add_filter1 = '//*[text()="Add filter"]';
        this.others = '[title="OTHERS"]';
        this.others1 = '[title="Others"]';
        this.email_option = '[title="is_email_verified"]';
        this.login_option = '.FaSelect_hoveredOption__Cs1tw';
        this.segment_namefield = '//*[@placeholder="Eg- Paid search visitors"]';
        this.seg_name = '.flex-col > :nth-child(7)';
        this.seg_rename = '//*[@placeholder="Name"]';
        this.save1 = '(//span[text()="Save"])[2]';
        this.save2 = '(//span[text()="Save"])[1]';
        this.Automation = '//h4[text()="Automations"]';
        this.create_new = '//div[text()="Create New"]';
        this.Account_click = '.active';
        this.alert_page = '.ant-form';
        this.select_event = '//span[text()="Select Event"]';
        this.Website_activity = '[title="Website activity"]';
        this.search_1 = '[placeholder="Search"]';
        this.pricing_option = '[title="www.factors.ai/pricing"]';
        this.save_css = ':nth-child(1) > :nth-child(2) > .flex > .ant-btn-primary';
        this.equals = '.FaFilterSelect_filter__1EYq7 > :nth-child(2) > .ant-btn';
        this.equals_value = '[title="<"]';
        this.enter_value = '[trigger="hover"]';
        this.add_filter_css = '.fa--query_block--actions-cols > .relative > .ant-btn';
        this.filter_search = '.fa-filter-select';
        this.Company_country = '(//div[@title="Company country"])[1]';
        this.select_city = '.FaSelect_dropdown__select__1L5kx > .undefined';
        this.United_Kingdom = '[title="United Kingdom"]';
        this.United_States = '[title="United States"]';
        this.Alert_name = '#alert_name';
        this.Add_property = '.ant-col > .ant-btn';
        this.property_search = '.fa-filter-select > .ant-input-affix-wrapper';
        this.Company_option = '(//div[@title="Company name"])[1]';
        this.page_referrer_URL = '(//div[@title="Page Referrer URL"])[1]';
        this.Enable_button = '(//button[@role="switch"])[1]';
        this.Select_channel = '//span[text()="Select Channel"]';
        this.search_channel = '[placeholder="Select channels"]';
        this.choose_channel = '//div[text()="#alert-test-staging"]//preceding::input[@type="checkbox"][1]';
        this.save_channel = '//span[text()="Close"]//following::button';
        this.submit = '(//button[@type="submit"])[2]';
        this.delete_alert = '//h4[text()=`${testName}`]//following::button[1]';
        this.remove_alert = '//span[text()="Remove alert"]';
        this.Ok = '//span[text()="OK"]';
        this.select_property = '[placeholder="Select Property"]';
        this.Add_First_Event = '(//span[text()="Add First Event"])[2]';
        this.Website_Session = '[title="Website Session"]';
        this.add_new_3 = '(//*[text()="Add new"])[3]';
        this.All_Account = '[title="All Accounts"]';
        this.account_filter = '//input[@placeholder="Search"]//following::div[3]';
        this.false = '//span[text()="Clear all"]//following::div[1]';
        this.calender_css = '.query_card_open-add > :nth-child(1) > .QueryComposer_composer_footer__LVpKT > .fa-custom-datepicker > .ant-btn';
        this.choose_date = '[data-menu-id]';
        this.Run_analysis_css = '.query_card_open-add > :nth-child(1) > .QueryComposer_composer_footer__LVpKT > .ant-btn-primary';
        this.Add_KPI = '(//span[text()="Add a KPI"])[2]';
        this.Add_a_KPI = '//span[text()="Add a KPI"]';
        this.Total_Session = '[title="Total Sessions"]';
        this.Channel_option = '[title="Channel"]';
        this.cal_1 = '.query_card_open-add > :nth-child(1) > .KPIComposer_composer_footer__2DZvK > .fa-custom-datepicker > .ant-btn';
        this.run_analysis_KPI = '.query_card_open-add > :nth-child(1) > .KPIComposer_composer_footer__2DZvK > .ant-btn-primary > span';
        this.table_validation1 = 'tbody.ant-table-tbody > tr:nth-child(2) > td:nth-child(1)';
        this.table_validation2 = 'tbody.ant-table-tbody > tr:nth-child(3) > td:nth-child(1)';
        this.open_account = '(//div[text()="infosys.com"])[1]//following::span[text()="Open"][1]';
        this.BirdView = '//span[text()="Birdview"]';
        this.View_visible = '.timeline-view';
        this.Expand = '//span[text()="Birdview"]//following::button[2]';
        this.collapse = '//span[text()="Birdview"]//following::button[3]';
        this.First_value = '//*[contains(text(),"infosys")]//following::div[@class="tag"][1]';
        this.Birdview_option = '//span[text()="Birdview"]//following::button[4]';
        this.Company_Created = '//h4[text()="Company Created"]';
        this.Event_validation = ':nth-child(1) > .bg-gradient--44px.pb-NaN > .timeline-events';
        this.Birdview_properties = '#rc-tabs-1-tab-properties > .fa-activity-filter--tabname';
        this.Birdview_properties_option = '//input[@placeholder="Select a User Property"]//following::div[7]';
        this.property_validation = '//*[text()="Date and Time"]//following::h4[2]';
        this.Birdview_properties_option1 = '//input[@placeholder="Select a User Property"]//following::div[11]';
        this.Company_domain_delete = '//h4[text()="Company domain"]//following::button[1]';
        this.Add_Property1 = '//*[text()="Add property"]';
        this.Company_Identification = '[title="Company Identification"]';
        this.company_identification_1 = '[title="Company identification"]';
        this.Company_domain = '[title="Company domain"]';
        this.time_dropdown = '//span[text()="Birdview"]//following::button[5]';
        this.timestamp_validation = ':nth-child(1) > :nth-child(1) > .timestamp';
        this.Time_stamp = '//*[text()="Timestamp"]';
        this.Hourly = '//*[text()="Hourly"]';
        this.Weekly = '//*[text()="Weekly"]';
        this.Monthly = '//*[text()="Monthly"]';
        this.Daily = '//*[text()="Daily"]';
        this.Time_line = '//*[text()="Timeline"]';
        this.Time_line_Validation = '#rc-tabs-0-panel-timeline';
        this.Over_view = '//*[text()="Overview"]';
        this.Over_view_validation = '.overview';
        this.people_firstvalue = '//th[text()="Date and Time"]//following::span[1]';
        this.popupcard = '.ant-popover-inner';
        this.Contact_List = '//h4[text()="Contact List"]';
        this.Milestones = '//*[text()="Milestones"]';
        this.Milestones_option1 = '//input[@placeholder="Select Upto 5 Milestones"]//following::div[11]';
        this.Milestones_option2 = '//input[@placeholder="Select Upto 5 Milestones"]//following::div[27]';
        this.Milestones_option3 = '//input[@placeholder="Select Upto 5 Milestones"]//following::div[31]';
        this.notification_popup2 = '.ant-notification-notice-with-icon';
        this.Apply2 = '//*[text()="Apply"]';
        this.City_delete = '//h4[text()="User City"]//following::button[1]';
        this.email_delete = '//h4[text()="email"]//following::button[1]';
        this.email = '[title="email"]';
        this.User_identification = '[title="User identification"]';
        this.User_City = '[title="User City"]';
        this.Send_Once = '#share-modal-form_subscriptionType > :nth-child(1)';
        this.copy_Link = '//span[text()="Copy link"]';
        this.Clear_All_Filter = '//h1[text()="Clear all filters"]';
        this.Discard_Filter = '//span[text()="Discard changes"]';
        this.clear_search = '//form[@id="basic"]//following::button[1]';
        this.New_Segment = '//h4[text()="New Segment"]';
        this.save_segment_css = '.py-4 > .ant-btn-default';
        this.save_field = '.flex > .ant-input';
        this.Company_Country = '//h4[text()="Company Country"]';
        this.In_Hubspot = '[title="In Hubspot"]';
        this.Hide_Filter = '.w-full > .ant-btn-text';
        this.attributes_pageload1 = '#card-36000268';
        this.attributes_pageload2 = '#card-36000426';
        this.Add_Report = '//span[text()=" Add Report"]';
        this.Add_Report_1 = '//Div[text()="Add Report"]';
        this.Add_KPI1 = '//span[text()="Add KPI"]';
        this.Users = '[title="Users"]';
        this.Filter_this_Attribute = '//h4[text()="CONVERSION GOALS"]//following::button[2]';
        this.Filter_By = '//*[text()="Filter By"]';
        this.Tactic = '[value="Tactic"]';
        this.Offer = '[value="Offer"]';
        this.Tactic_Offer = '[value="TacticOffer"]';
        this.Add_a_Property = '//span[text()="Add a Property"]';
        this.Campaign1 = '[title="Campaign"]';
        this.Add_Model = '//span[text()="Add Model"]';
        this.First_Touch = '[title="First Touch"]';
        this.Add_Compare_Model = '//h4[text()="Attribution Model"]//following::button[2]';
        this.Last_Touch = '[title="Last Touch"]';
        this.cal_attri = '.AttrQueryComposer_composer__footer__X33eZ > .fa-custom-datepicker > .ant-btn';
        this.Last_7_days = '//a[text()="Last 7 days"]';
        this.Run_Analysis1 = '//span[text()="Run Analysis"]';
        this.Attri_pageloaded = '.mt-24';
        this.Dashboards = '//h4[text()="Dashboards"]';
        this.Dashboards_Title = '#fa-at-text--dashboard-title';
        this.New_Reports = '//div[text()="New Reports"]';
        this.Event_Report = '//div[text()="New Event Report"]';
        this.web_options = ':nth-child(2) > .flex-row > :nth-child(2) > .ant-typography';
        this.Sparkline = '//span[text()="Sparkline"]';
        this.Line_Chart = '//h1[text()="Line Chart"]';
        this.Filter_this_event = '(//h4[text()="EVENTS"])[2]//following::button[3]';
        this.session_properties = '[title="Session properties"]';
        this.Session_Landing_Page_URL = '[title="Session Landing Page URL"]';
        this.breakdown_option = '(//h4[text()="EVENTS"])[2]//following::button[2]';
        this.BreakDown = '//span[text()="Breakdown"]';
        this.Traffic_source = '[title="Traffic source"]';
        this.Session_Exit_Page_URL = '[title="Session Exit Page URL"]';
        this.Content_Groups = '//h4[text()="Content Groups"]';
        this.Add_New = '//span[text()="Add New"]';
        this.Add_new2 = '//span[text()="Add new"]';
        this.content_group_name = '#content_group_name';
        this.content_group_description = '#content_group_description';
        this.New_Value = '//span[text()="New value"]';
        this.New_value_1 = '//span[text()="New Value"]';
        this.content_group_value = '#content_group_value';
        this.Add_Rule = '//span[text()="Add rule"]';
        this.page_value = '#rule_0_va';
        this.Or_value = '[value="OR"]';
        this.Contains = '[title="Contains"]';
        this.Equals = '[title="Equals"]';
        this.equals_1 = '[title="equals"]';
        this.Delete_option = '//th[text()="Values"]//following::button[1]';
        this.Remove = '//a[text()="Remove"]';
        this.confirm_1 = '//span[text()="Confirm"]';
        this.Customs_KPIs = '//h4[text()="Custom KPIs"]';
        this.Name = '#name';
        this.description = '#description';
        this.Default = '[title="Default"]';
        this.Derived_KPI = '[title="Derived KPI"]';
        this.Select_Event = '[placeholder="Select Event"]';
        this.Add_another_KPI = '//span[text()="Add another KPI"]';
        this.KPI_option_1 = '//input[@placeholder="Select Event"]//following::div[4]';
        this.Formula = '#for';
        this.showAspercentage = '#showAspercentage';
        this.Remove_1 = '//span[text()="Remove"]';
        this.Engagements = '//h4[text()="Engagements"]';
        this.Engagement_Category = '//span[text()="Engagement Category"]';
        this.Hot_Input = '//h4[text()="Hot"]//following::input[1]';
        this.Warm_Input = '//h4[text()="Warm"]//following::input[1]';
        this.Cool_Input = '//h4[text()="Cool"]//following::input[1]';
        this.Apply_Changes1 = '//span[text()="Apply Changes"]';
        this.Apply_changes_2 = '//span[text()="Apply changes"]';
        this.Reset_to_Default = '//span[text()="Reset to Default"]';
        this.Add_signal = '//span[text()="Add signal"]';
        this.Add_signal_1 = '//span[text()="Add Signal"]';
        this.Pricing_page_visit_Search = '[placeholder="Eg: Pricing page visit"]';
        this.Assign_weight = '//h4[text()="Assign weight"]//following::span[3]';
        this.Last_page = '//li[@title="Next Page"]//preceding::li[1]';
        this.Yes = '//span[text()="Yes"]';
        this.Pricing = '//h4[text()="Plans & Billings"]';
        this.Integrations = '//h4[text()="Integrations"]';
        this.Acc_Iden_enrich = '//h4[text()="Account Identification"]//following::div[5]';
        this.upgrade_plan = '.mt-5 > .ant-btn';
        this.upgrade_title = '.fai-text__size--h4';
        this.Buy_this_Plan = '(//span[text()="Buy this Plan"])[1]';
        this.Enrichment_Rules = '//div[text()="EnrichmentRules"]';
        this.Set_custom_rules = '//h4[text()="Set up rules for Account identification"]//following::label[2]';
        this.Select_Pages = '//span[text()="Select pages"]';
        this.Upload_List = '//span[text()="Upload List"]';
        this.File = '//a[text()="file"]';
        this.File_Upload = 'input[type="file"]';
        this.Done = '//span[text()="Done"]';
        this.Enrichment_page_validation = ':nth-child(4) > .flex-col > :nth-child(2)';
        this.Save_Changes = '//span[text()="Save changes"]';
        this.close_new = '//h4[text()="Identify accounts who visited specific pages"]//following::button[2]';
        this.Delete = '//span[text()="Delete"]';
        this.Delete_1 = '(//span[text()="Delete"])[2]';
        this.Event = '//h4[text()="Events"]';
        this.New_Event = '//span[text()="New Event"]';
        this.Event_Title = '.ant-form > :nth-child(1) > :nth-child(1) > .ant-typography';
        this.Source = '#source';
        this.Hubspot = '[title="Hubspot"]';
        this.Object_type = '#object_type';
        this.Contact = '[title="contact"]';
        this.Property_name = '#property_name';
        this.City = '[title="city"]';
        
        this.Record_modified_time = '//span[text()="Record modified time"]';
        this.Save_1 = '//span[text()="Save"]';
        this.Popup_Message = '.ant-message-notice-content';
        this.Event_option = '(//span[text()="hubspot"])[1]//following::button[1]';
        this.Remove_Event = '//a[text()="Remove Event"]';
        this.New_Report_CSS = '#fa-at-btn--new-report';
        this.Funnel_Report = '//div[text()="New Funnel Report"]';
        this.Add_another_event = '(//span[text()="Add another event"])[2]';
        this.Add_another_event_1 = '//span[text()="Add another event"]';
        this.Linkedin_Company_Engagements = '[title="Linkedin Company Engagements"]';
        this.Linkedin_Ad_Clicked = '[title="Linkedin Ad Clicked"]';
        this.Filter_By_CSS = '.query_card_open-add > :nth-child(1) > :nth-child(4)';
        this.Filter_this_funnel = '(//h4[text()="Analyse"])[2]//following::button[3]';
        this.Delete_this_funnel = '(//h4[text()="Analyse"])[2]//following::button[8]';
        this.Add_New_FilterBy = '(//h4[text()="FILTER BY"])[2]//following::span[text()="Add new"][1]';
        this.Add_New_FilterBy1 = '//h4[text()="FILTER BY"]//following::span[text()="Add new"][1]';
        this.Plus_Button = '(//h4[text()="FILTER BY"])[2]//following::button[@index="0"]';
        this.Visited_G2 = '[title="Visited G2"]';
        this.Or = '(//h4[text()="FILTER BY"])[2]//following::h4[1]';
        this.or_1 = '(//h4[text()="Filter by"])[2]//following::h4[1]';
        this.Add_New_Breakdown = '(//h4[text()="BREAKDOWN"])[2]//following::span[text()="Add new"]';
        this.Add_New_Breakdown1 = '(//h4[text()="BREAKDOWN"])//following::span[text()="Add new"]';
        this.Engagement_Level = '[title="Engagement Level"]';
        this.Conversion_Window = '(//h4[text()="Conversion within"])[2]//following::div[1]';
        this.Tooltip = '[role="tooltip"]';
        this.Date_select = '(//div[@role="tooltip"]//following::span)[2]';
        this.Hours = '[title="Hours"]';
        this.Minutes = '[title="Minutes"]';
        this.Days = '[title="Days"]';
        this.calender_MenuList = '(//h4[text()="FUNNEL CRITERIA"])[2]//following::button[1]';
        this.Menu_Item = '[role="menuitem"]';
        this.Run_Anal = '(//span[text()="Run Analysis"])[2]';
        this.CSVlink = '#csvLink';
        this.Top_Engagement_Signals = '[title="Top Engagement Signals"]';
        this.Select_Month = '//a[text()="Select Month"]';
        this.date_choosen = '[title="2024-01"]';
        this.Break_up = '//div[text()="Break-up"]';
        this.Breakup_Search = '//div[text()="Break-up"]//following::button[1]';
        this.Report_Name = '[placeholder="Report Name"]';
        this.Description_OP = '[placeholder="Description (Optional)"]';
        this.Closed = '(//span[text()="Close"])[1]';
        this.close_2 = '//span[text()="Close"]';
        this.Drafts = '//h4[text()="Drafts"]';
        this.Saved_report_option = '//th[text()="Date"]//following::button[1]';
        this.Delete_Report = '//*[text()="Delete Report"]';
        this.Add_to_Dashboard = '//span[text()="Add to Dashboard"]';
        this.Please_Select = '//span[text()="Please Select"]';
        this.Automation_1 = '[title="Automation"]';
        this.Create_New_Report = '//h3[text()="Create New Report"]';
        this.Automation_Folder = '//h1[text()="Automation folder"]';
        this.Automate = '//h4[text()="Automation"]';
        this.Automation_Delete = '//h4[text()="Data from"]//following::button[4]';
        this.Delete_Widget = '//a[text()="Delete Widget"]';
        this.Compare = '//h4[text()="Compare"]';
        this.Compare_to = '//h4[text()="Compare with:"]//following::li[2]';
        this.Hubspot_Companies = '[title="Hubspot Companies"]';
        this.Table_Body =  '.ant-table-body';
        this.Table_Body_1 = '.ant-table-content';
        this.Save_Segment_1 = '//h1[text()="Save segment"]';
        this.Paid_search_visitors = '[placeholder="Eg- Paid search visitors"]';
        this.Insight = '//h4[text()="Insights"]';
        this.Account = '(//h4[text()="Accounts"])[2]';
        this.Touchpoints = '//h4[text()="Touchpoints"]';
        this.Hubspot_1 = '//div[text()="Hubspot"]';
        this.Create_a_touchpoint_using_Contact = '//h4[text()="Create a touchpoint using"]//following::div[2]';
        this.Campaigns = '[title="Campaigns"]';
        this.Add_Filter_1 = '//span[text()="Add Filter"]';
        this.Select_Type_Property = '(//div[text()="Select Type Property"])[1]';
        this.Tactic_1 = '[title="Tactic"]';
        this.Select_Source_Property = '(//div[text()="Select Source Property"])[1]';
        this.Select_Campaign_Property = '(//div[text()="Select Campaign Property"])[1]';
        this.Select_Channel_Property = '(//div[text()="Select Channel Property"])[1]';
        this.Touchpoints_Delete_option = '//th[text()="Property Mapping"]//following::button[3]';
        this.Touchpoints_Delete = '//a[text()="Delete"]';
        this.Email_tracking = '//div[text()="Email tracking"]';
        this.Search_type = '[type="search"]';
        this.Copy_Hubspot_UTM_Parameter = '//h4[text()="Hubspot"]//following::button[1]';
        this.Add_Email_tracking = '//td[text()="User Email ID"]//following::button[1]';
        this.utm_tag = '#utm_tag';
        this.Properties = '//h4[text()="Properties"]';
        this.Verified_saved_UTM = '//h4[text()="Hubspot"]//following::code[3]/span';
        this.X_close = '(//span[text()="Testing"])[1]/span';
        this.Open_Accenture_Acc = '//div[text()="accenture.com"]//following::span[text()="Open"][1]';
        this.Page_View_1 = '(//div[text()="Page View"])[1]';
        this.Channel_timeline = '(//div[text()="Channel:"])[1]//following::div[1]';
        this.Page_view_validation = '.ant-drawer-body';
        this.Company_State_button = '//h4[text()="Company State"]//following::button[1]';
        this.Add_Property_1 = '(//span[text()="Add property"])[2]';
        this.Company_State = '[title="Company State"]';        
        this.Event_Properties = '//span[text()="Event Properties"]';
        this.Page_URL_Button = '//h4[text()="Page URL"]//following::button[1]';
        this.Channel_Button = '//h4[text()="Channel"]//following::button[1]';
        this.Details = '//span[text()="Timeline"]//following::td[4]'
        this.Page_Properties = '[title="Page properties"]';
        this.page_URL = '[title="Page URL"]';
        this.Templates = '//span[text()="Templates"]';
        this.Account_Executives = '(//div[text()="Account Executives"])[2]';
        this.This_is_correct = '//span[text()="This is correct"]';
        this.Performs_an_event = '[title="Performs an event"]';
        this.Enter_the_segment = '[title="Enter the segment"]';
        this.segment_name_1 = '//h4[text()="Segment name"]//following::div[3]';
        this.segment_name_2 = '//h4[text()="Segment name"]//following::span[2]';
        this.In_Hubspot_text = '//div[text()="In Hubspot"]';
        this.Add_property_title = '#rcDialogTitle0';
        this.Value = '#value';
        this.Date_Range = '#date_range';
        this.New_Filter = '//span[text()="New Filter"]';
        this.Select_Property_text = '//span[contains(text(),"Select Property")]';
        this.Name_text = '//span[text()="name"]';
        this.Create_new_alert_title = '//h3[text()="Create new alert"]';
        this.Filter_Input = '//h4[text()="Filters"]//following::input[@type="text"]';
        this.Cancel = '(//span[text()="Cancel"])[1]';
        this.Remove_Property = '//a[text()="Remove Property"]';
        this.KPI_Report = '//div[text()="New KPI Report"]';
        this.KPI_Cal = '(//h4[text()="BREAKDOWN"])[2]//following::button[2]';
        this.KPI_Selection_option = '(//span[text()="Close"])[1]//preceding::button[3]';
        this.Share_to_slack = '//span[text()="Share to Slack"]';
        this.slackShare_channel = '#slackShare_channel';
        this.alert_test_staging = '[title="#alert-test-staging"]';
        this.slackShare_message = '#slackShare_message';
        this.Email_this_report = '//span[text()="Email this report"]';
        this.emailShare_email = '#emailShare_email';
        this.emailShare_message = '#emailShare_message';
        this.Path_Analysis = '//h4[text()="Path Analysis"]';
        this.Explain = '//h4[text()="Explain"]';
        this.Path_Analysis_Pageload = ':nth-child(2) > .ant-col';
        this.Explain_pageload = '.ant-row > :nth-child(2)';
        this.Create_New_PathAna = '.ant-col-4 > .flex > .ant-btn';
        this.Start_with_an_event_title = '[title="Start with an event"]';
        this.Start_with_an_event = '//div[text()="Start with an event"]';
        this.Add_Event_1 = '(//span[text()="Add Event"])[1]';
        this.All_events_except_title = '[title="All events except"]';
        this.All_events_except = '//div[text()="All events except"]';
        this.Company_Created_title = '[title="Company Created"]';
        this.Steps = '//h4[text()="Show"]//following::div[2]';
        this.Four_steps = 'div[title="4 Steps"]';
        this.Select_date_range = '//span[text()="Select date range"]';
        this.Preview_Month = '//input[@placeholder="Start date"]//following::button[4]';
        this.Start_Date = '(//div[text()="2"])[1]';
        this.End_Date = '(//div[text()="15"])[1]';
        this.Save_and_Build = '//span[text()="Save and Build"]';
        this.Basic_title = '[id="basic_title"]';
        this.Basic_description = '[id="basic_description"]';
        this.Building_Validation = '(//*[text()="Title"]//following::tr//td)[2]';
        this.Journey_Option = '//*[text()="Title"]//following::button[1]';
        this.Only_specific_events = '//div[text()="Only specific events"]';
        this.If_the_event_equals_title = '[title="If the event equals"]';
        this.If_the_event_equals = '//div[text()="If the event equals"]';
        this.Path_Select_event = '//h4[text()="In this path, Show"]//following::input[3]';
        this.G2_Engagement_option = '//div[text()="G2 Engagements"]//following::div[2]';
        this.If_the_event_is_of_type = '//div[text()="If the event is of type"]';
        this.Path_Select_event_1 = '//h4[text()="In this path, Show"]//following::input[5]';
        this.Page_Views = '[title="Page Views"]';
        this.Explain_CreateNew = '.justify-between > .ant-btn > span';
        this.Select_Analysis_Window = '.fa-custom-datepicker > .ant-btn';
        this.Last_7_days = '//a[text()="Last 7 days"]';
        this.Add_Event_explain = '//span[text()="Add Event"]';
        this.Hubspot_Contacts = '[title="Hubspot Contacts"]';
        this.Contact_List_1 = '[title="Contact List"]';
        this.Profile_Report = '//div[text()="New Profile Report"]';
        this.Add_New_1 = '(//span[text()="Add New"])[2]';
        this.Website_Visitors = '[title="Website Visitors"]';
        this.Filte_this_Profile = '(//h4[text()="PROFILES TO ANALYSE"])[2]//following::button[3]';
        this.Equals_text = '(//span[text()="equals"])[2]';
        this.Delete_this_Profile = '(//h4[text()="PROFILES TO ANALYSE"])[2]//following::button[4]';
        this.Add_Plus_button = '(//h4[text()="Filter by"])[2]//following::button[5]';
        this.BreakDown_AddNew = '(//h4[text()="BREAKDOWN"])[2]//following::span[text()="Add new"][1]';
        this.Profile_report_gen = '.mt-12 > .justify-center';
        this.Country = '[title="Country"]';
        this.Country1 = '[title="country"]';
        this.Country_Search_result = '(//div[text()="Country"]//following::tbody//td)[5]';
        this.Profile_Report_option = '//h4[contains(text(),"Reports")]//following::button[1]';
        this.Add_to_Dashboard_title = '//h4[text()="Add to Dashboard"]';
        this.Save_2 = '(//span[text()="Save"])[3]';
        this.Account_text = '//span[text()="Accounts"]';
        this.cart_submit = '[data-cb-id="cart_submit"]';
        this.first_name = '[id="first_name"]';
        this.Next = '[class="cb-button cb-button__primary"]';
        this.Subscribe = '[data-cb-id="review_submit"]';
        this.View_Report = '//div[text()="View Report"]';
        this.Expand_1 = '//span[text()="Expand"]';
        this.Save_dropdown = '//span[text()="Save"]//following::button[1]';
        this.Save_as_New = '//span[text()="Save as New"]';
        this.Delete_Report_1 = '(//a[text()="Delete Report"])[1]';
        this.Add_another_KPI_1 = '(//span[text()="Add another KPI"])[2]';
        this.Weekly_updates = '//h4[text()="Weekly updates"]';
        this.operator = '#operator';
        this.is_greater_than = '//div[text()="is greater than"]';
        this.Remove_Alert_option = '//th[text()="Status"]//following::button[1]';
        this.Remove_Breakdown = '//*[text()="BREAKDOWN"]//following::button[2]';
        this.Remove_FilterBy = '//*[text()="FILTER BY"]//following::button[4]';
        this.Remove_FilterBy1 = '(//*[text()="FILTER BY"])[2]//following::button[4]';
        this.Remove_Breakdown1 = '(//*[text()="BREAKDOWN"])[2]//following::button[2]';
        this.Overwrite = '//span[text()="Yes, overwrite it"]';
    }
}

export default new locators();