class locators {

  constructor() {

    this.Account_FirstValue = '//*[text()="Account Domain"]//following::tr[2]/td[1]';
    this.Account_value = '//div[text()="Open"]//following::div[1]';
    this.Account_value_Close = '//div[text()="Open"]//following::button[2]';
    this.Open_NewTab = '(//div[@class="flex justify-between items-center"]//*[local-name()="svg"])[2]';
    this.account_dropdown = '#fa-at-link--accounts';
    this.account = '.ant-dropdown > .ant-dropdown-menu > li:nth-child(${item.index}) > span > a';
    this.Account_Pagetitle = '//h1[text()="All Accounts"]';
    this.weekly_Updates_Title = '#fa-at-text--page-title';
    this.Page_title1 = '#fa-at-text--page-title';
    this.workflows_Title = '(//h4[text()="Workflows"])[2]';
    this.WorkFlows = '//h4[text()="Workflows"]';
    this.all_People_Title = '//h3[.="All People"]';
    this.segment_Alert_Title = '//h3[.="Real time alerts"]';
    this.attribution_Pagetitle = '//h4[.="Attribution Reports"]';
    this.account_identification_Title = '//h4[text()="Top accounts that visited your website"]';
    this.Page_title = '.fai-text__size--h4';
    this.Attribute_title = '//h4[text()="Project Settings"]//following::h4[13]';
    this.report_dropdown = '#fa-at-link--journeys';
    this.attributes = '//h4[text()="Attribution"]';
    this.configure = '#fa-at-dropdown--config';
    this.configure_dropdown = '.fa-at-overlay--config > ul > li:nth-child(${item.index}) > span > a';
    this.usermail = '#fa-at-dropdown--projects div.opacity-80';
    this.setting = '#fa-at-dropdown--settings';
    this.pricing_breadcrumb = '.ant-breadcrumb';
    this.billing = '.ant-breadcrumb span:nth-child(3) > span.ant-breadcrumb-link';
    this.Account_identification = '//h4[text()="Account identification"]';
    this.identi_table = '.ant-table-container';
    this.Identification_Table = '.data-table';
    this.table_row1 = '.ant-table-tbody > :nth-child(1) > :nth-child(1)';
    this.table_row2 = '.ant-table-tbody > :nth-child(2) > :nth-child(1)';
    this.channel = '.gap-4 > :nth-child(1) > .ant-btn';
    this.channel_dropdown = '.fa-select-dropdown > .flex';
    this.Organic_Search = '[title="Organic Search"]';
    this.organic_table1 = '.ant-table-tbody > :nth-child(1) > :nth-child(2)';
    this.organic_table2 = '.ant-table-tbody > :nth-child(2) > :nth-child(2)';
    this.organic_table3 = '.ant-table-tbody > :nth-child(3) > :nth-child(2)';
    this.direct = '[title="Direct"]';
    this.paid_search = '[title="Paid Search"]';
    this.campaign = '.gap-4 > :nth-child(2) > div > .ant-btn';
    this.campaign_dropdown = '.fa-select-dropdown';
    this.TD_Search_Remarketing_Competitors = '[title="TD_Search_Remarketing_Competitors"]';
    this.Apply = '.fa-select--buttons > .ant-btn';
    this.TD_Search_US_Deanon_Competition = '[title="TD_Search_US_Deanon_Competition"]';
    this.page_view = '.gap-4 > :nth-child(3) > div > .ant-btn';
    this.pageview_dropdown = '.FaSelect_dropdown__select__1L5kx';
    this.pageview_option1 = '//input[@placeholder="Search"]//following::div[3]';
    this.pageview_option2 = '//input[@placeholder="Search"]//following::div[6]';
    this.pageview_option3 = '//input[@placeholder="Search"]//following::div[7]';
    this.pageview_option4 = '//input[@placeholder="Search"]//following::div[9]';
    this.pageview_option5 = '//input[@placeholder="Search"]//following::div[4]';
    this.pageview_option6 = '//input[@placeholder="Search"]//following::div[5]';
    this.Upgrade_validation = '.ant-modal-body';
    this.Filter_option2 = '//input[@placeholder="Select Property"]//following::div[4]';
    this.Filter_option1 = '//input[@placeholder="Select Property"]//following::div[3]';
    this.identi_table1 = '.ant-table-wrapper';
    this.calender = '//h4[text()="Channel"]//following::button[3]';
    this.select_date = '//div[@title="Today"]//following::div[3]';
    this.share = '.justify-between.align-middle > :nth-child(2)';
    this.share1 = '//span[text()="Share"]'
    this.email_field = '#share-modal-form_emails_0';
    this.done = '[type="submit"]';
    this.Continue = '//*[text()="Continue"]';
    this.notification_popup = '.ant-notification-notice';
    this.notification_popup1 = '.ant-notification-notice-message';
    this.notification_popup3 = '.ant-notification';
    this.clear = '.FaSelect_dropdown__clear_opt__263i6 > .ant-btn';
    this.search = '//div[text()="Top accounts"]//following::button[1]';
    this.search_field = '[placeholder="Search"]';
    this.Klenty_details = '.ant-table-row > :nth-child(1)';
    this.X_button = '.DataTable_searchBar__1fGz4 > .justify-between > :nth-child(2) > :nth-child(1) > .ant-btn';
    this.download = '//div[text()="Top accounts"]//following::button[2]';
    this.account_pageloaded = ':nth-child(2) > .ant-table-cell-fix-left';
    this.factors_File = '(//tbody//tr//descendant::a)[1]';
    this.search_button = '.relative > .ant-btn';
    this.search_area = '//*[@placeholder="Search Account"]';
    this.download_button = '//span[text()="Filter"]//following::button[2]';
    this.People_download_button = '//span[text()="Filter"]//following::button[2]';
    this.download_header = '//input[@placeholder="Search properties"]//preceding::h4[1]';
    this.exportCSV = '//span[text()="Export CSV"]';
    this.filter = '.w-full > .ant-btn';
    this.view_filter = '.justify-center > span';
    this.filter_css = '.w-full > .ant-btn-text';
    this.Add_filter = '(//*[text()="Add filter"])[1]';
    this.add_New_Button_Wrkflw = '//div//button//span[text()="Add new"]';
    this.select_Accountprop = '.FaSelect_hoveredOption__Cs1tw';
    this.Visited_Website = '[title="Visited Website"]';
    this.true = '[title="True"]';
    this.true1 = '[title="true"]';
    this.Add_event = '//*[text()="Add event"]';
    this.Event_performed = '.fa-select-dropdown > .flex-col > :nth-child(5)';
    this.select_option = '//input[@placeholder="Select Event"]//following::div[3]';
    this.Apply_Changes = '//span[text()="Apply filter"]';
    this.filter_closebtn = '//*[@placeholder="Search Users"]//following::button[1]';
    this.save_segment = '//h1[text()="Save as Segment"]';
    this.segment_name = '.flex > .ant-input';
    this.segment_rename = '[placeholder="Name"]';
    this.Save = '//*[text()="Save"]';
    this.Search_segment = '[placeholder="Search segment"]';
    this.Saved_segment = '//input[@placeholder="Search segment"]//following::div[2]';
    this.Select_segment = '//span[text()="New Segment"]//preceding::div[6]';
    this.Threedots = '//h1[contains(text(),"filter(s)")]//following::div[3]';
    this.Threedots1 = '//div[@class="FolderStructure_folder_item_actions__3tUoG"]';
    this.rename_segment = '//div[@class="ant-popover-inner-content"]//div[@class="FolderStructure_popover_list__3XG-n"][2]';
    this.Delect_segment = '(//div[text()="Delete segment"])[2]';
    this.Delete_segment1 = '(//div[text()="Delete segment"])[1]';
    this.confirm = '//*[text()="Confirm"]';
    this.Add_column_1 = '//span[text()="Filter"]//following::button[3]';
    this.Table_properties = '.ant-popover-inner-content';
    this.company_name = '[data-id="Company Name"]';
    this.Apply1 = '//span[text()="Apply"]';
    this.People = '//h4[text()="People"]';
    this.Search1 = '//*[@placeholder="Search Users"]';
    this.rowname = '.ant-table-row > .ant-table-cell-fix-left';
    this.Add_column = '//span[text()="Filter"]//following::button[3]';
    this.table_property = '.ant-tabs';
    this.company_name1 = '//h4[text()="Company Country"]';
    this.CompanyCountryISOCode = '(//h4[text()="Company Country ISO Code"])[1]';
    this.row_validation = '.ant-table-cell-content > .flex';
    this.Add_filter1 = '//*[text()="Add filter"]';
    this.others = '[title="OTHERS"]';
    this.others1 = '[title="Others"]';
    this.email_option = '[title="is_email_verified"]';
    this.login_option = '[title="LOGIN"]';
    this.segment_namefield = '//*[@placeholder="Eg- Paid search visitors"]';
    this.seg_name = '.flex-col > :nth-child(7)';
    this.seg_rename = '//*[@placeholder="Name"]';
    this.save1 = '(//span[text()="Save"])[2]';
    this.save2 = '(//span[text()="Save"])[1]';
    this.Automation = '//h4[text()="Automations"]';
    this.create_new = '(//div[text()="Create New"])[1]';
    this.Account_click = '.active';
    this.alert_page = '.ant-form';
    this.select_event = '//h4[text()="Event details"]//following::span[text()="Select Event"]';
    this.select_event_1 = '//span[text()="Select Event"]';
    this.Website_activity = '[title="Website activity"]';
    this.search_1 = '[placeholder="Search"]';
    this.pricing_option = '[value="www.factors.ai/pricing"]';
    this.pricing_option = '.FaSelect_hoveredOption__Cs1tw > .truncate > b';
    this.save_css = ':nth-child(1) > :nth-child(2) > .flex > .ant-btn-primary';
    this.equals = '.FaFilterSelect_filter__1EYq7 > :nth-child(2) > .ant-btn';
    this.equals_value = '[title="<"]';
    this.enter_value = '[trigger="hover"]';
    this.add_filter_css = '.fa--query_block--actions-cols > .relative > .ant-btn';
    this.filter_search = '.fa-filter-select';
    this.Company_country = '(//div[@title="Hubspot Company Company Name"])[1]';
    this.select_city = '.FaSelect_dropdown__select__1L5kx > .undefined';
    this.United_Kingdom = '[title="United Kingdom"]';
    this.United_States = '[title="United States"]';
    this.Alert_name = '#alert_name';
    this.Add_property = '.ant-col > .ant-btn';
    this.property_search = '.fa-filter-select > .ant-input-affix-wrapper';
    this.Company_option = '(//div[@title="Company Name"])[1]';
    this.page_referrer_URL = '(//div[@title="Page Referrer URL"])[1]';
    this.Enable_button = '(//button[@role="switch"])[1]';
    this.Select_channel = '//span[text()="Select Channel"]';
    this.search_channel = '[placeholder="Select channels"]';
    this.choose_channel = '//div[text()="#alert-test-staging"]//preceding::input[@type="checkbox"][1]';
    this.save_channel = '//span[text()="Close"]//following::button';
    this.submit = '(//button[@type="submit"])[2]';
    this.delete_alert = '//h4[text()=`${testName}`]//following::button[1]';
    this.remove_alert = '//span[text()="Remove alert"]';
    this.Ok = '//span[text()="OK"]';
    this.select_property = '[placeholder="Select Property"]';
    this.Add_First_Event = '(//span[text()="Add First Event"])[2]';
    this.Website_Session = '[title="Website Session"]';
    this.add_new_3 = '(//*[text()="Add new"])[3]';
    this.All_Account = '[title="All Accounts"]';
    this.account_filter = '(//input[@placeholder="Search"]//following::div[3])[1]';
    this.account_filter1 = '(//input[@placeholder="Search"]//following::div[3])[2]';
    this.false = '//span[text()="Clear all"]//following::div[1]';
    this.calender_css = '.query_card_open-add > :nth-child(1) > .QueryComposer_composer_footer__LVpKT > .fa-custom-datepicker > .ant-btn';
    this.choose_date = '[data-menu-id]';
    this.Run_analysis_css = '.query_card_open-add > :nth-child(1) > .QueryComposer_composer_footer__LVpKT > .ant-btn-primary';
    this.Add_KPI = '(//span[text()="Add a KPI"])[2]';
    this.Add_a_KPI = '//span[text()="Add a KPI"]';
    this.Total_Session = '[title="Total Sessions"]';
    this.Total_Session_Attri = '//div[@class="flex flex-col"]//child::div[1]';
    this.Channel_option = '[title="Channel"]';
    this.cal_1 = '.query_card_open-add > :nth-child(1) > .KPIComposer_composer_footer__2DZvK > .fa-custom-datepicker > .ant-btn';
    this.run_analysis_KPI = '.query_card_open-add > :nth-child(1) > .KPIComposer_composer_footer__2DZvK > .ant-btn-primary > span';
    this.table_validation1 = 'tbody.ant-table-tbody > tr:nth-child(2) > td:nth-child(1)';
    this.table_validation2 = 'tbody.ant-table-tbody > tr:nth-child(3) > td:nth-child(1)';
    this.open_account = '(//a[text()="infosys.com"])//following::button[1]';
    this.BirdView = '//span[text()="Birdview"]';
    this.View_visible = 'tbody > :nth-child(2)';
    this.Expand = '//span[text()="Birdview"]//following::button[2]';
    this.collapse = '//span[text()="Birdview"]//following::button[3]';
    this.First_value = '//*[text()="Date and Time"]//following::div[@class="tag"][1]';
    this.Birdview_option = '//span[text()="Birdview"]//following::button[4]';
    this.Company_Created = '//h4[text()="Company Created"]';
    this.Event_validation = ':nth-child(1) > .bg-gradient--44px.pb-NaN > .timeline-events';
    this.Birdview_properties = '#rc-tabs-1-tab-properties > .fa-activity-filter--tabname';
    this.Birdview_properties_option = '//input[@placeholder="Select a User Property"]//following::div[7]';
    this.property_validation = '//*[text()="Date and Time"]//following::h4[2]';
    this.Birdview_properties_option1 = '//input[@placeholder="Select a User Property"]//following::div[11]';
    this.Company_domain_delete = '//h4[text()="Company Domain"]//following::button[1]';
    this.Add_Property1 = '//span[text()="Add property"]';
    this.Company_Identification = '[title="Company Identification"]';
    this.company_identification_1 = '[title="Company identification"]';
    this.Company_domain = '[title="Company Domain"]';
    this.time_dropdown = '//span[text()="Birdview"]//following::button[5]';
    this.timestamp_validation = ':nth-child(1) > :nth-child(1) > .timestamp';
    this.Time_stamp = '//*[text()="Timestamp"]';
    this.Hourly = '//*[text()="Hourly"]';
    this.Weekly = '//*[text()="Weekly"]';
    this.Monthly = '//*[text()="Monthly"]';
    this.Daily = '//*[text()="Daily"]';
    this.Time_line = '//*[text()="Timeline"]';
    this.Time_line_Validation = '#rc-tabs-0-panel-timeline';
    this.Over_view = '//*[text()="Overview"]';
    this.Over_view_validation = '.overview';
    this.people_firstvalue = '//th[text()="Date and Time"]//following::span[1]';
    this.popupcard = '.ant-popover-inner';
    this.Contact_List = '//h4[text()="Contact List"]';
    this.Milestones = '//*[text()="Milestones"]';
    this.Milestones_option1 = '//input[@placeholder="Select Upto 5 Milestones"]//following::div[11]';
    this.Milestones_option2 = '//input[@placeholder="Select Upto 5 Milestones"]//following::div[27]';
    this.Milestones_option3 = '//input[@placeholder="Select Upto 5 Milestones"]//following::div[28]';
    this.notification_popup2 = '.ant-notification-notice-with-icon';
    this.Apply2 = '//*[text()="Apply"]';
    this.enrich_delete = '//h4[.="Enrichment Source"]/..//following::button[1]'
    this.City_delete = '//h4[text()="User City"]//following::button[1]';
    this.email_delete_1 = '//h4[text()="email"]//following::button[1]';
    this.email_delete_opt = '//h4[.="email"]/../..//button';
    this.email = '[title="email"]';
    this.email_1 = '[title="is_email_verified"]';
    this.User_identification = '[title="User Identification"]';
    this.User_City = '[title="User City"]';
    this.Send_Once = '#share-modal-form_subscriptionType > :nth-child(1)';
    this.copy_Link = '//span[text()="Copy link"]';
    this.Clear_All_Filter = '//h1[text()="Clear all filters"]';
    this.Discard_Filter = '//span[text()="Discard changes"]';
    this.clear_search = '//form[@id="basic"]//following::button[1]';
    this.New_Segment = '//span[text()="New Segment"]';
    this.save_segment_css = '//h1[text()="Save segment"]';
    this.save_field = '//div[@class="flex flex-col gap-y-2"]//input[@placeholder="Eg- Paid search visitors"]';
    this.Company_Country = '(//h4[text()="Company Country"])[1]';
    this.first_seendate = '//h4[text()="First Seen Date"]'
    this.In_Hubspot1 = '[title="In Hubspot"]';
    this.Hide_Filter = '.w-full > .ant-btn-text';
    this.attributes_pageload1 = '(//div[contains(@id,"card")])[1]';
    this.attributes_pageload2 = '#card-36000426';
    this.Add_Report = '//span[text()=" Add Report"]';
    this.Add_Report_1 = '//Div[text()="Add Report"]';
    this.Add_KPI1 = '//span[text()="Add KPI"]';
    this.Users = '[title="Users"]';
    this.Filter_this_Attribute = '//h4[text()="CONVERSION GOALS"]//following::button[2]';
    this.Filter_By = '//*[text()="Filter By"]';
    this.Tactic = '[value="Tactic"]';
    this.Offer = '[value="Offer"]';
    this.Tactic_Offer = '[value="TacticOffer"]';
    this.Add_a_Property = '//span[text()="Add a Property"]';
    this.Campaign1 = '[title="Campaign"]';
    this.Add_Model = '//span[text()="Add Model"]';
    this.First_Touch = '[title="First Touch"]';
    this.Add_Compare_Model = '//h4[text()="Attribution Model"]//following::button[2]';
    this.Last_Touch = '[title="Last Touch"]';
    this.cal_attri = '.AttrQueryComposer_composer__footer__X33eZ > .fa-custom-datepicker > .ant-btn';
    this.Last_7_days = '//a[text()="Last 7 days"]';
    this.Run_Analysis1 = '//span[text()="Run Analysis"]';
    this.Attri_pageloaded = '.mt-12';
    this.Dashboards = '//h4[text()="Dashboards"]';
    this.Dashboards_Title = '#fa-at-text--dashboard-title';
    this.Draft_Title = '#fa-at-text--draft-title';
    this.New_Reports = '//div[text()="New Reports"]';
    this.Event_Report = '//h4[text()="New Event Report"]';
    this.web_options = ':nth-child(2) > .flex-row > :nth-child(2) > .ant-typography';
    this.Sparkline = '//span[text()="Sparkline"]';
    this.Line_Chart = '//h1[text()="Line Chart"]';
    this.Filter_this_event = '(//h4[text()="EVENTS"])[2]//following::button[3]';
    this.session_properties = '[title="Session Properties"]';
    this.Session_Landing_Page_URL = '[title="Session Landing Page URL"]';
    this.breakdown_option = '(//h4[text()="EVENTS"])[2]//following::button[2]';
    this.BreakDown = '//span[text()="Breakdown"]';
    this.Traffic_source = '[title="Traffic Source"]';
    this.Traffic_source_1 = '//h4[.="Traffic Source"]';
    this.Session_Exit_Page_URL = '[title="Session Exit Page URL"]';
    this.Content_Groups = '//div[text()="Content Groups"]';
    this.Add_New = '//span[text()="Add New"]';
    this.Add_new2 = '//span[text()="Add new"]';
    this.content_group_name = '#content_group_name';
    this.content_group_description = '#content_group_description';
    this.New_Value = '//span[text()="New value"]';
    this.New_value_1 = '//span[text()="New Value"]';
    this.content_group_value = '#content_group_value';
    this.Add_Rule = '//span[text()="Add rule"]';
    this.page_value = '#rule_0_va';
    this.Or_value = '[value="OR"]';
    this.Contains = '[title="Contains"]';
    this.Equals = '[title="Equals"]';
    this.equals_1 = '[title="equals"]';
    this.Delete_option = '//th[text()="Values"]//following::button[1]';
    this.Remove = '//a[text()="Remove"]';
    this.confirm_1 = '//span[text()="Confirm"]';
    this.Customs_KPIs = '#rc-tabs-0-tab-customKPI';
    this.Name = '#name';
    this.description = '#description';
    this.Default = '[title="Default"]';
    this.Derived_KPI = '[title="Derived KPI"]';
    this.Select_Event = '[placeholder="Select Event"]';
    this.Add_another_KPI = '//span[text()="Add another KPI"]';
    this.KPI_option_1 = '//input[@placeholder="Select Event"]//following::div[4]';
    this.Formula = '#for';
    this.showAspercentage = '#showAspercentage';
    this.Remove_1 = '//span[text()="Remove"]';
    this.Account_Scoring = '//h4[text()="Account Scoring"]';
    this.Engagements = '//h4[text()="Engagements"]';
    this.Engagement_Category = '//span[text()="Engagement Category"]';
    this.Hot_Input = '//span[text()="Hot"]//following::input[1]';
    this.Warm_Input = '//span[text()="Warm"]//following::input[1]';
    this.Cool_Input = '//span[text()="Cool"]//following::input[1]';
    this.Apply_Changes1 = '//span[text()="Apply Changes"]';
    this.Apply_changes_2 = '//span[text()="Apply changes"]';
    this.Reset_to_Default = '//span[text()="Reset to Default"]';
    this.Add_signal = '//span[text()="Add signal"]';
    this.Add_signal_1 = '//span[text()="Add Signal"]';
    this.Pricing_page_visit_Search = '//textarea[contains(text(),"Untitled")]';
    this.Assign_weight = '//span[text()="70"]';
    this.Assign_weight1 = '//span[text()="60"]';
    this.Last_page = '//li[@title="Next Page"]//preceding::li[1]';
    this.Yes = '//span[text()="Yes"]';
    this.Pricing = '//h4[text()="Plans & Billings"]';
    this.Integrations = '//h4[text()="Integrations"]';
    this.Enrichment_Source = '[title="Enrichment Source"]';
    this.clearbit_api = '[title="clearbit_api"]';
    this.Acc_Iden_enrich = '//h4[text()="Account Identification"]//following::div[5]';
    this.upgrade_plan = '.mt-5 > .ant-btn';
    this.upgrade_title = '.fai-text__size--h4';
    this.Buy_this_Plan = '(//span[text()="Buy this Plan"])[1]';
    this.Enrichment_Rules = '//div[text()="Enrichment Rules"]';
    this.Set_custom_rules = '//span[@class="ant-radio"]//input';
    this.Select_Pages = '//span[text()="Select pages"]';
    this.Upload_List = '//span[text()="Upload List"]';
    this.File = '//a[text()="file"]';
    this.File_Upload = 'input[type="file"]';
    this.Done = '//span[text()="Done"]';
    this.UploadandContinue = '//span[text()="Upload and Continue"]';
    this.Enrichment_page_validation = ':nth-child(4) > .flex-col > :nth-child(2)';
    this.Save_Changes = '//span[text()="Save Changes "]';
    this.Savechanges1 = '//span[text()="Save changes"]';
    this.close_new = '//h4[text()="Identify accounts who visited specific pages"]//following::button[2]';
    this.Delete = '//a[text()="Delete Report"]';
    this.Delete_enrich = '//span[.="Delete"]';
    this.Delete_1 = '(//span[text()="Delete"])[2]';
    this.Event = '//div[text()="Custom Events"]';
    this.PropertyMapping = '//div[text()="Property Mapping"]'
    this.Custom_Definitions = '//h4[text()="Custom Definitions"]';
    this.New_Event = '//span[text()="New Event"]';
    this.Event_Title = '.ant-form > :nth-child(1) > :nth-child(1) > .ant-typography';
    this.Source = '#source';
    this.Hubspot = '[title="Hubspot"]';
    this.Object_type = '#object_type';
    this.Contact = '[title="contact"]';
    this.Deal = '[title="deal"]';
    this.Affiliate_Partner = '[title="affiliate_partner"]';
    this.Property_name = '#property_name';
    this.City = '[title="city"]';
    this.Record_modified_time = '//span[text()="Record modified time"]';
    this.Save_1 = '//span[text()="Save"]';
    this.Popup_Message = '.ant-message-notice-content';
    this.Event_option = '(//span[text()="hubspot"])[1]//following::button[1]';
    this.Remove_Event = '//a[text()="Remove Event"]';
    this.New_Report_CSS = '#fa-at-btn--new-report';
    this.Funnel_Report = '//h4[text()="New Funnel Report"]';
    this.Add_another_event = '(//span[text()="Add another event"])[2]';
    this.Add_another_event_1 = '//span[text()="Add another event"]';
    this.Linkedin_Company_Engagements = '[title="Linkedin Company Engagements"]';
    this.Linkedin_Ad_Clicked = '[title="Linkedin Ad Clicked"]';
    this.Filter_By_CSS = '.query_card_open-add > :nth-child(1) > :nth-child(4)';
    this.Filter_this_funnel = '(//h4[text()="Analyse"])[2]//following::button[3]';
    this.Delete_this_funnel = '(//h4[text()="Analyse"])[2]//following::button[8]';
    this.Add_New_FilterBy = '(//h4[text()="FILTER BY"])[2]//following::span[text()="Add new"][1]';
    this.Add_New_FilterBy1 = '//h4[text()="FILTER BY"]//following::span[text()="Add new"][1]';
    this.Plus_Button = '(//h4[text()="FILTER BY"])[2]//following::button[@index="0"]';
    this.Visited_G2 = '[title="Visited G2"]';
    this.Or = '(//h4[text()="FILTER BY"])[2]//following::h4[1]';
    this.or_1 = '(//h4[text()="Filter by"])[2]//following::h4[1]';
    this.Add_New_Breakdown = '(//div[@class="flex relative"]//button)[2]';
    this.Add_New_Breakdown_new = '.m-0 > .flex > .ant-btn > span';
    this.Engagement_Level = '[title="Engagement Level"]';
    this.Conversion_Window = '(//h4[text()="Conversion within"])[2]//following::div[1]';
    this.Tooltip = '[role="tooltip"]';
    this.Date_select = '(//div[@role="tooltip"]//following::span)[2]';
    this.Hours = '[title="Hours"]';
    this.Minutes = '[title="Minutes"]';
    this.Days = '[title="Days"]';
    this.calender_MenuList = '(//h4[text()="FUNNEL CRITERIA"])[2]//following::button[1]';
    this.Menu_Item = '[role="menuitem"]';
    this.Run_Anal = '(//span[text()="Run Analysis"])[1]';
    this.CSVlink = '//div[text()="Break-up"]//following::button[2]';
    this.Downloadcsv = '//div[text()="Break-up"]//following::button[3]';
    this.Top_Engagement_Signals = '[title="Top Engagement Signals"]';
    this.Select_Month = '//a[text()="Select Month"]';
    this.date_choosen = '//*[contains(@title,"01")]';
    this.Break_up = '//div[text()="Break-up"]';
    this.Breakup_Search = '//div[text()="Break-up"]//following::button[1]';
    this.Report_Name = '[placeholder="Report Name"]';
    this.Description_OP = '[placeholder="Description (Optional)"]';
    this.Closed = '(//span[text()="Close"])[1]';
    this.close_2 = '//span[text()="Close"]';
    this.Drafts = '//h4[text()="Drafts"]';
    this.Saved_report_option = '//th[text()="Date"]//following::button[1]';
    this.Delete_Report = '//*[text()="Delete Report"]';
    this.Add_to_Dashboard = '//span[text()="Add to Dashboard"]';
    this.Please_Select = '//span[@class="ant-select-selection-placeholder"]';
    this.Automation_1 = '[title="Automation Dashboard"]';
    this.Automation_dashboard_Folder = '(//div[text()="Automation"])[1]'
    this.Create_New_Report = '//h3[text()="Create New Report"]';
    this.Automation_Folder = '//h1[text()="Automation folder"]';
    this.Automate = '//span[text()="Automation Dashboard"]';
    this.Automate_dashboard = '(//div[text()="Automation Dashboard"])[2]';
    this.Automation_Delete = '//h4[text()="Data from"]//following::button[4]';
    this.Delete_Widget = '//a[text()="Delete Widget"]';
    this.Compare = '//h4[text()="Compare"]';
    this.Compare_to = '//h4[text()="Compare with:"]//following::li[2]';
    this.Hubspot_Companies = '[title="Hubspot Companies"]';
    this.Table_Body = '.ant-table-body';
    this.Table_Body_1 = '.ant-table-content';
    this.Save_Segment_1 = '//h1[text()="Save segment"]';
    this.Campaign_Groups = '//div[text()="Campaign Groups"]';
    this.Paid_search_visitors = '[placeholder="Eg- Paid search visitors"]';
    this.Insight = '//h4[text()="Insights"]';
    this.List = '//h4[text()="List"]';
    this.Account = '(//h4[text()="Accounts"])[2]';
    this.Touchpoints = '//h4[text()="Touchpoints Definitions"]';
    this.Hubspot_1 = '//div[text()="Hubspot"]';
    this.Salesforce = '//div[text()="Salesforce"]';
    this.Create_a_touchpoint_using_Contact = '//h4[text()="Create a touchpoint using"]//following::button[1]';
    this.Campaigns = '[title="Campaigns"]';
    this.Add_Filter_1 = '//span[text()="Add Filter"]';
    this.Select_Type_Property = '(//div[text()="Select Type Property"])[1]';
    this.Tactic_1 = '[title="Tactic"]';
    this.Select_Source_Property = '(//div[text()="Select Source Property"])[1]';
    this.Select_Campaign_Property = '(//div[text()="Select Campaign Property"])[1]';
    this.Select_Channel_Property = '(//div[text()="Select Channel Property"])[1]';
    this.Touchpoints_Delete_option = '//th[text()="Property Mapping"]//following::button[6]';
    this.Touchpoints_Delete = '//span[text()="Delete"]';
    this.Email_tracking = '//div[text()="Email tracking"]';
    this.Search_type = '//span[text()="Select Platform"]';
    this.Copy_Hubspot_UTM_Parameter = '//h4[text()="Hubspot"]//following::button[1]';
    this.Add_Email_tracking = '//td[text()="User Email ID"]//following::button[1]';
    this.utm_tag = '#utm_tag';
    this.Properties1 = '//h4[text()="Properties"]';
    this.Verified_saved_UTM = '(//span[text()="Testing"][text()="{{contact.email}}"])[1]';
    this.X_close = '(//span[text()="Testing"])[1]/span';
    this.Open_Accenture_Acc = '//a[text()="accenture.com"]//following::button[1]';
    this.Page_View_1 = '(//div[text()="Page View"])[1]';
    this.Channel_timeline = '(//div[text()="Channel:"])[1]//following::div[1]';
    this.Page_view_validation = '.ant-drawer-body';
    this.Company_State_button = '//h4[text()="Company State"]//following::button[1]';
    this.Add_Property_1 = '(//span[text()="Add property"])[2]';
    this.Add_Property_2 = '(//span[text()="Add property"])[1]';
    this.Add_Property_3 = '//span[text()="User Properties"]//following::span[text()="Add property"]';
    this.Company_State = '[title="Company State"]';
    this.Event_Properties = '//span[text()="Event Properties"]';
    this.Page_URL_Button = '//h4[text()="Page URL"]//following::button[1]';
    this.Channel_Button = '//h4[text()="Channel"]//following::button[1]';
    this.Page_Domain = '//div[@class="flex flex-col"]//div[2]';
    this.Details = '(//td//span[text()="www.factors.ai"])[1]'
    this.Page_Properties = '[title="Page Properties"]';
    this.Page_domain_option = '[title="Page Domain"]';
    this.page_URL = '[title="Page URL"]';
    this.Templates = '//span[text()="Templates"]';
    this.Account_Executives = '//button[text()="Account Executives"]';
    this.This_is_correct = '//span[text()="This is correct"]';
    this.Performs_an_event = '[title="Performs an event"]';
    this.Enter_the_segment = '[title="Enter the segment"]';
    this.segment_name_1 = '//h4[text()="Segment name"]//following::div[3]';
    this.segment_name_2 = '//h4[text()="Segment name"]//following::span[2]';
    this.In_Hubspot_text = '//div[text()="In Hubspot"]';
    this.Add_property_title = '#rcDialogTitle0';
    this.Value = '#value';
    this.Date_Range = '#date_range';
    this.New_Filter = '//span[text()="New Filter"]';
    this.Select_Property_text = '//span[contains(text(),"Select Property")]';
    this.Name_text = '//span[text()="name"]';
    this.Create_new_alert_title = '//h3[text()="Create new alert"]';
    this.Filter_Input = '//h4[text()="Filters"]//following::input[@type="text"]';
    this.Cancel = '(//span[text()="Cancel"])[1]';
    this.Remove_Property = '//span[text()="Remove Property"]';
    this.KPI_Report = '//h4[text()="New KPI Report"]';
    this.KPI_Cal = '(//h4[text()="BREAKDOWN"])[2]//following::button[2]';
    this.KPI_Selection_option = '//tbody//tr//td[4]//button';
    this.close_kpi = '#app-header > .justify-between > :nth-child(2) > .ant-btn-default > span';
    this.Share_to_slack = '//a[text()="Share to Slack"]';
    this.slackShare_channel = '#slackShare_channel';
    this.alert_test_staging = '[title="#alert-test-staging"]';
    this.slackShare_message = '#slackShare_message';
    this.Email_this_report = '//a[text()="Email this report"]';
    this.emailShare_email = '#emailShare_email';
    this.emailShare_message = '#emailShare_message';
    this.Path_Analysis = '//h4[text()="Path Analysis"]';
    this.Explain = '//h4[text()="Explain"]';
    this.Path_Analysis_Pageload = ':nth-child(2) > .ant-col';
    this.Explain_pageload = '.ant-row > :nth-child(2)';
    this.Create_New_PathAna = '.ant-col-4 > .flex > .ant-btn';
    this.Start_with_an_event_title = '[title="Start with an event"]';
    this.Start_with_an_event = '//div[text()="Start with an event"]';
    this.Add_Event_1 = '(//span[text()="Add Event"])[1]';
    this.All_events_except_title = '[title="All events except"]';
    this.All_events_except = '//div[text()="All events except"]';
    this.Company_Created_title = '[title="Company Created"]';
    this.Steps = '//h4[text()="Show"]//following::div[2]';
    this.Four_steps = 'div[title="4 Steps"]';
    this.Select_date_range = '//span[text()="Select date range"]';
    this.Preview_Month = '//input[@placeholder="Start date"]//following::button[4]';
    this.Start_Date = '(//div[text()="2"])[1]';
    this.End_Date = '(//div[text()="15"])[1]';
    this.Save_and_Build = '//span[text()="Save and Build"]';
    this.Basic_title = '[id="basic_title"]';
    this.Basic_description = '[id="basic_description"]';
    this.Building_Validation = '(//*[text()="Title"]//following::tr//td)[2]';
    this.Journey_Option = '//*[text()="Title"]//following::button[1]';
    this.Only_specific_events = '//div[text()="Only specific events"]';
    this.If_the_event_equals_title = '[title="If the event equals"]';
    this.If_the_event_equals = '//div[text()="If the event equals"]';
    this.Path_Select_event = '//h4[text()="In this path, Show"]//following::input[3]';
    this.G2_Engagement_option = '//div[text()="Company Created"]';
    this.If_the_event_is_of_type = '//div[text()="If the event is of type"]';
    this.Path_Select_event_1 = '//h4[text()="In this path, Show"]//following::input[5]';
    this.Page_Views = '[title="Page Views"]';
    this.Explain_CreateNew = '.justify-between > .ant-btn > span';
    this.Select_Analysis_Window = '.fa-custom-datepicker > .ant-btn';
    this.Last_7_days = '//a[text()="Last 7 days"]';
    this.Add_Event_explain = '//span[text()="Add Event"]';
    this.Hubspot_Contacts = '[title="Hubspot Contacts"]';
    this.Contact_List_1 = '[title="Contact List"]';
    this.Profile_Report = '//h4[text()="New Profile Report"]';
    this.Add_New_1 = '(//span[text()="Add New"])[2]';
    this.Website_Visitors = '[title="Website Visitors"]';
    this.Filte_this_Profile = '(//h4[text()="PROFILES TO ANALYSE"])[2]//following::button[3]';
    this.Equals_text = '(//span[text()="equals"])[2]';
    this.Delete_this_Profile = '(//h4[text()="PROFILES TO ANALYSE"])[2]//following::button[4]';
    this.Add_Plus_button = '(//h4[text()="Filter by"])[2]//following::button[5]';
    this.BreakDown_AddNew = '(//h4[text()="BREAKDOWN"])[2]//following::span[text()="Add new"][1]';
    this.Profile_report_gen = '.mt-12 > .justify-center';
    this.Country = '[title="Country"]';
    this.Country1 = '[title="country"]';
    this.Country_Search_result = '(//div[text()="Company Country"]//following::td)[5]';
    this.Profile_Report_option = '//h4[contains(text(),"Reports")]//following::button[1]';
    this.Add_to_Dashboard_title = '//h4[text()="Add to Dashboard"]';
    this.Save_2 = '(//span[text()="Save"])[2]';
    this.Save_3 = '(//span[text()="Save"])[3]';
    this.Account_text = '//span[text()="Accounts"]';
    this.cart_submit = '[data-cb-id="cart_submit"]';
    this.first_name = '[id="first_name"]';
    this.Next = '[class="cb-button cb-button__primary"]';
    this.Subscribe = '[data-cb-id="review_submit"]';
    this.View_Report = '//li[@role="menuitem"]//span//div[text()="View Report"]';
    this.Expand_1 = '//span[text()="Expand"]';
    this.Save_dropdown = '//span[text()="Save"]//following::button[1]';
    this.Save_as_New = '//span[text()="Save as New"]';
    this.Delete_Report_1 = '(//a[text()="Delete Report"])[1]';
    this.Add_another_KPI_1 = '(//span[text()="Add another KPI"])[1]';
    this.Weekly_updates = '//h4[text()="Weekly updates"]';
    this.operator = '#operator';
    this.is_greater_than = '//div[text()="is greater than"]';
    this.Remove_Alert_option = '//th[text()="Status"]//following::button[1]';
    this.Remove_Breakdown = '//*[text()="BREAKDOWN"]//following::button[2]';
    this.Remove_FilterBy = '//*[text()="FILTER BY"]//following::button[4]';
    this.Remove_FilterBy1 = '(//*[text()="FILTER BY"])[1]//following::button[4]';
    this.Remove_Breakdown1 = '(//*[text()="BREAKDOWN"])[2]//following::button[2]';
    this.Overwrite = '//span[text()="Yes, overwrite it"]';
    this.InHubspot = '//span[text()="In Hubspot"]';
    this.workflow = "//div[text()='New Workflow']";
    this.Hubspot_template = '//input[@placeholder="Search"]//following::h4[text()="Add or update HubSpot companies"]';
    this.Salesforce_template = '//input[@placeholder="Search"]//following::h4[text()="Add or update Salesforce accounts"]';
    this.Use_this_template = '//span[text()="Use this workflow"]';
    this.workflow_edit_icon = '(//h4[text()="Add or update HubSpot companies"])[1]/div'
    this.workflow_edit_icon1 = '(//h4[text()="Add or update Salesforce accounts"])[1]/div'
    this.workflow_name = '//textarea[contains(text(),"Add or update HubSpot companies")]';
    this.workflow_name1 = '//textarea[contains(text(),"Add or update Salesforce accounts")]';
    this.Zoho_workflow_name = '//textarea[contains(text(),"Add or update Zoho companies")]';
    this.Action_flow = '.flex items-start justify-between px-6 py-6';
    this.Configure_Action = '//span[text()="Configure Action"]';
    this.Configurations_dropdown = '//div[text()="Configurations"]';
    this.Website_activity = '[title="Website activity"]';
    this.configurations_field = '//div[text()="Configurations"]//following::div[3]';
    this.Factors_Properties1 = '//h4[text()="Factors Properties"]//following::input[1]';
    this.Factors_Properties2 = '//h4[text()="Factors Properties"]//following::input[2]';
    this.Factors_Properties3 = '//h4[text()="Factors Properties"]//following::input[3]';
    this.Factors_Properties4 = '//h4[text()="Factors Properties"]//following::input[4]';
    this.factors_option1 = '//div[text()="OTHERS"]//following::div[2]';
    this.factors_option2 = '//div[text()="OTHERS"]//following::div[4]';
    this.Account_ID = '[title="Account ID"]';
    this.Deleted = '[title="Deleted"]';
    this.add_icon = '//div[@class="ant-col"]//img';
    this.Hubspot_company_name = '[title="Hubspot Company Company Name"]';
    this.Companyname_hubspot = '[title="Company name"]';
    this.Hubspot_company_domain_name = '[title="Hubspot Company Company Domain Name"]';
    this.Hubspot_contact_Email_domain = '[title="Hubspot Contact Email Domain"]';
    this.Company_domain_name = '[title="Company Domain Name"]';
    this.SaveandPublish1 = '(//span[text()="Save and Publish"])[2]';
    this.SaveandPublish = '(//span[text()="Save and Publish"])[1]';
    this.Remove_workflow = '//span[text()="Remove workflow"]';
    this.Search_dashboard = '[placeholder="Search dashboard"]';
    this.property1 = '(//div//div//span//input)[3]';
    this.property2 = '(//span[@class="ant-select-arrow"]//span)[3]';
    this.property3 = '(//div//div//span//input)[5]';
    this.property4 = '(//div//div//span//input)[6]';
    this.property5 = '(//div//div//span//input)[7]';
    this.property6 = '(//div//div//span//input)[8]';
    this.property7 = '(//div//div//span//input)[9]';
    this.property8 = '(//div//div//span//input)[10]';
    this.company_Name_workflow = '[title="Company name"]';
    this.hubspot_Option = '//div[text()="Hubspot Contact Company Name"]';
    this.pageload_Confirmation = '#resizing-table-container-div';
    this.calender_Icon = '//div[@class="flex gap-x-1 items-center"]';
    this.ninety_days = '//span[text()="90"]';
    this.about_Us = '//div[.="About Us"]';
    this.form_Submissions = '//h4[text()="Form Submissions"]';
    this.touchpoint_Filter_Hubspot = '[title="Hubspot"]';
    this.offer = '[title="Offer"]';
    this.rename_segment1 = '(//div[text()="Edit segment Details"])[4]';
    this.campaign_title = '//main//div//div//h4[.="Smart Reach"]';
    this.add_New_Rule = '//div[.="Add New Rule"]//preceding::div[@class="ant-space-item"]';
    this.campaign_Inner_Page = '//main[@class="ant-layout-content bg-white py-6 px-8"]';
    this.campaign_Group = '//h4[.="Campaign Group"]';
    this.select_Campaign_Group = '//span[.="Select Campaign Groups"]';
    this.matched_Audience = '//div[@class="rc-virtual-list-holder-inner"]/div[3]';
    this.prospecting_Option = '//div[@class="rc-virtual-list-holder-inner"]/div[6]';
    this.edit_Icon = '//span[@aria-label="edit"]//*[name()="svg"]';
    this.rule_Title_Field = '//textarea[.="Untitled frequency cap rule"]';
    this.publish_Button = '//button[@id="fa-at-btn--new-report"]';
    this.success_Noti = '//div[@class="ant-notification-notice-message"]';
    this.active_Switch = '//div[@class="ant-row items-center"]';
    this.primer_Audience = '//div[contains(text(),"Primer Audience")]';
    this.gromo_Agency = '//div[contains(text(),"TD-Prospecting-Gromo+Agencies")]';
    this.dream_Data = '//div[@class="rc-virtual-list-holder-inner"]/div[2]';
    this.heap_Analytics = '//div[@class="rc-virtual-list-holder-inner"]/div[7]';
    this.published_verify = '(//span[.="published"])[1]';
    this.back_Button = '(//button[@type="button"])[2]';
    this.rule_Published = '//tbody/tr[1]/td[2]';
    this.meat_Ball_Icon = '(//td[@class="ant-table-cell"]//button)[1]';
    this.edit_Rule = '//a[text()="Edit rule"]';
    this.remove_Rule = '//a[text()="Remove rule"]';
    this.custom_Rules = '//div[@class="ant-collapse-header"]';
    this.toggle_Custom_Rules = '//div[@class="ant-collapse-header"]//button[@role="switch"]';
    this.add_Filter_Scroll = '//div[@class="ant-table-footer"]';
    this.add_Filter = '//h1[.="Add filter"]';
    this.all_Accounts_Opt = '//h4[.="All Accounts"]';
    this.hubspot_Opt = '[title="In Hubspot"]';
    this.true_Opt = '//h4[.="True"]';
    this.apply_Opt = '//span[text()="Apply"]';
    this.filter_Total_Click = '(//input[@value="0"])[1]';
    this.filter_Total_Impression = '.freq-capping_cap-table__RT7ec > .ant-table-wrapper > .ant-spin-nested-loading > .ant-spin-container > .ant-table > .ant-table-container > .ant-table-content > table > .ant-table-tbody > .ant-table-row > :nth-child(3) > .ant-input-number > .ant-input-number-input-wrap > .ant-input-number-input';
    this.hubspot_Cmpny_Opt = '//h4[text()="Hubspot Companies"]';
    this.hubspot_Cmpny_Url = '//h4[text()="Hubspot Company URL"]';
    this.hub_Url = '//h4[text()="https://app.hubspot.com/contacts/6188127/company/10177629796"]';
    this.publish_Button2 = '(//div[text()="Publish"])[2]';
    this.blinking_Check - '//td[@class="ant-table-cell"]//div//span//span[1]';
    this.delete_Noti = '//div[text()="Rule Successfully Deleted!"]';
    this.discard_Changes = '//div[@class="ant-row items-center"]//button//div//div[.="Discard Changes"]';
    this.all_Ad_Accounts = '//h4[text()="All Ad Accounts"]';
    this.total_click_Def_Criteria = '(//td[@class="ant-table-cell"]//div//div//input)[1]';
    this.total_Impression_Def_Criteria = '//input[@value="Timeout.sm"]';
    this.active_Toggle = '//span[normalize-space()="Active"]';
    this.pause_Noti = '//div[@class="ant-modal-content"]';
    this.pause_Option = '//span[normalize-space()="Pause"]';
    this.unpublished_option = '//span[contains(text(),"unpublished")]';
    this.confirm_Publish_Box = '//div[@class="ant-modal-body"]';
    this.confirm_Publish_Option = '//span[text()="Confirm Publish"]';
    this.primer_Check = '//span[contains(text(),"Primer Audience")]';
    this.gromo_Check = '//span[contains(text(),"TD-Prospecting-Gromo+Agencies")]';
    this.s_Campaigns_Dd = '//span[.="Select Campaigns"]';
    this.campaign_Option = '//span[@class="ant-radio-button ant-radio-button-checked"]';
    this.t2_Meatball = '//h4[.="t02"]/../..//td[3]//button';
    this.messageads_Option = '//div[@class="rc-virtual-list-holder-inner"]/div[3]';
    this.spotlight_Option = '//div[@class="rc-virtual-list-holder-inner"]/div[6]';
    this.second_imp = '(//tbody//tr//td//input)[6]';
    this.ruleone_Published = '//h4[.="ruleone"]/../..//td//span[text()="published"]';
    this.ruleone_Meatbutton = '//h4[.="ruleone"]/../..//td//button';
    this.global_Search = '//input[@placeholder="Search ⌘+K"]';
    this.global_Popup = '//div[@class="GlobalSearch_globalsearch-container__2Yu7H"]';
    this.ask_Factors = '//span[text()="Ask Factors"]';
    this.ai_Textfield = '//input[@placeholder="Ask AI anything..."]';
    this.kpi_Heading = '//h4[contains(text(),"Reports / KPI /")]';
    this.filter_By_Option = '(//h4[.="Filter by"])[2]';
    this.collapse_All = '//span[.="Collapse all"]';
    this.graph_View = '//div[@class="SparkLineChart_sparkChart__39Umc flex justify-center"]';
    this.Graph_Details = '//div[@class="mt-12"]';
    this.google_Adwords_Option = '(//div[.="Google Adwords"])[1]';
    this.social_Marketing_Option = '(//div[.="Paid Social Marketing"])[2]';
    this.global_Jumpto = '//input[@placeholder="Search or jump to"]';
    this.create_New_Segment = '//span[text()="Create New Segment"]';
    this.select_Template_Window = '//h4[text()="Start Fresh"]';
    this.segment_Page_Heading = '//h1[text()="Untitled Segment 1"]';
    this.NewUsers = '[title="New Users"]';
    this.Count = '[title="Count"]';
    this.Add_another_KPI2 = '(//span[text()="Add another KPI"])[2]';
    this.FilterthisKPI = '(//h4[text()="KPI TO ANALYSE"])[2]//following::button[3]';
    this.companyRegion = '[title="Company Region"]';
    this.FilterthisKPI1 = '(//h4[text()="B"])[2]//following::button[3]';
    this.FilterthisKPI2 = '(//h4[text()="B"])//following::button[3]';
    this.Properties = '[title="Properties"]';
    this.BreakDownProperty = '//input[@placeholder="Select Property"]//following::div[3]';
    this.KPI_Cal1 = '(//h4[text()="BREAKDOWN"])[2]//following::button[4]';
    this.LastWeek = "//a[text()='Last Week']";
    this.userName = '[title="User Name"]';
    this.UserContinent = '[title="User Continent"]';
    this.KPI1Selected = '(//h4[text()="A"])//following::span[2]';
    this.FilterByName = '(//h4[text()="Filter by"])[3]//following::span[1]';
    this.FilterByName2 = '(//h4[text()="Filter by"])[2]//following::span[1]';
    this.FilterByName3 = '(//h4[text()="Filter by"])[1]//following::span[1]';
    this.KPI2Selected = '(//h4[text()="B"])//following::span[2]';
    this.KPI3Selected = '(//h4[text()="C"])//following::span[2]';
    this.FilterByName1 = '(//h4[text()="Filter by"])[4]//following::span[1]';
    this.BreakDownName = '((//h4[text()="BREAKDOWN"])[2]//following::span[2])[1]';
    this.BreakDownName1 = '//h4[text()="BREAKDOWN"]//following::span[2]';
    this.CalenderCheck = '(//div[text()="from"])//following::button[1]';
    this.ChartCheck = '(//div[text()="from"])//following::span[2]';
    this.Metric = '//h1[text()="Metric"]';
    this.EngagedUsers = '[title="Engaged Users"]';
    this.UserPostalCode = '[title="User Postal Code"]';
    this.FilterByName5 = '(//h4[text()="and"])//following::span[1]';
    this.GlobalSearch = '[placeholder="Search ⌘+K"]';
    this.InternalSearch = '[placeholder="Search or jump to"]';
    this.SelectSavedReport = '//h4[text()="Saved Reports"]//following::div[1]';
    this.KPIDashboard = '//span[text()="Web KPIs and Overview"]';
    this.SavedDate = '//h4[text()="Data from"]//following::span[1]';
    this.FirstKPIReport = '//h4[text()="Data from"]//following::h4[2]';
    this.threedot_icon = '.FolderStructure_folder_item_actions__3tUoG';
    this.dashoboardpage_Title = '//h4[text()="Google Adwords"]';
    this.engaged_User_Option = '[title="Engaged Users"]';
    this.session_Medium_Option = '//div[@title="Session Medium" and @class="flex flex-row items-center"]';
    this.filter_Funnel = '//div[@class="relative"]//button[@type="button"]';
    this.select_Values_Option = '//div[@class="fa-select-group-select--options  "]';
    this.os_Version_Option = '//span[@class="truncate"]';
    this.user_Name = '//b[text()="User Name"]';
    this.user_Last_Name = '//div[@class="flex flex-col"]//div';
    this.user_State_Option = '//b[text()="User State"]';
    this.abu_Dhabi = '[title="Abu Dhabi"]';
    this.three_dot_create_Alias = '(//div[@class="flex "]//button//*[local-name()="svg"])[6]';
    this.create_Alias = '//span[@class="ant-dropdown-menu-title-content"]//span[.="Create Alias"]';
    this.alias_Text_Field = '[placeholder="Alias title"]';
    this.create_Option = '//span[.="Create"]';
    this.run_Analysis_New = '//div[@class="fa-custom-datepicker"]//following::button//following::span[.="Run Analysis"]';
    this.edit_Alias = '//span[text()="Edit Alias"]';
    this.update_Option = '//span[text()="Update"]';
    this.alias_Name_Verify = '(//h4[text()="KPI TO ANALYSE"])[2]//following::h4[2]';
    this.compare = '//h4[text()="Compare"]';
    this.previous_Day = '//h4[text()="Previous Day"]';
    this.previous_30_Days = '//h4[text()="Previous 30 Days"]';
    this.daily_Trend = '//button//span[text()="Daily Trend"]';
    this.weekly_Trend = '//span[text()="Weekly Trend"]';
    this.quarterly_Trend = '//span[text()="Quarterly Trend"]';
    this.column = '//h1[text()="Column"]';
    this.chart_Arrow = '(//div[@class="flex items-center gap-x-2"]//button[@type="button"]//*[local-name()="svg"])[4]';
    this.Please_Select_Hubspot_Option = '//div[text()="Blogs Conversion Summary (With HubSpot)"]';
    this.three_dot_Edit_Alias = '.query_composer > :nth-child(1) > :nth-child(1) > .ant-collapse > .ant-collapse-item > .ant-collapse-content > .ant-collapse-content-box > :nth-child(1) > [data-id="0"] > .QueryBlock_query_block__t4tNb > .QueryBlock_query_block__event__2Psl5 > .ml-8 > .ant-dropdown-trigger';
    this.session_Os = '(//b[.="Session OS"])[1]';
    this.user_Name_Option = '[title="User Name"]';
    this.not_Set_Option = '//b[text()="Not Set"]/..';
    this.alias_Check = '//div[contains(@class,"rounded-lg")]/..//h4';
    this.datepicker1 = '(//div[@class="calendar"]//div[@class="fa-custom-datepicker"])[1]';
    this.datepicker2 = '(//div[@class="calendar"]//div[@class="fa-custom-datepicker"])[2]';
    this.cal_Selector = '//ul[@role="menu"]//li[6]';
    this.table_Check = '//div[@class="data-table"]';
    this.company_Industtry = '[title="Company Industry"]';
    this.break_Table_heading = '//div[text()="Break-up"]';
    this.company_option = '//h4[.="Company Identification"]';
    this.brkdwn_Cancel = '(//h4[text()="BREAKDOWN"])[2]//following::button[2]';
    this.select_template = '//h4[text()="Select a Template"]'
    this.Missing_Integration_appears_popup = '//div[@class="ant-popover-inner-content"]/div'
    this.Create_segement = '//h4[text()="Trials and Customers engaging with feature content"]//following::span[1]'
    this.Add_Filters = '(//h1[text()="Add filter"])[1]'
    this.Add_Filters_value = '//h4[text()="Company Identification"]'
    this.Add_Filters_value_searchbar = '(//span[text()="Select Property"]//following::input)[1]'
    this.Add_Filters_value1 = '//b[text()="Company Country ISO Code"]'
    this.Add_live = '//h4[text()="100ms.live"]'
    this.Add_Event = '//h1[text()="Add event"]'
    this.Add_Event_hubshot = '//h4[text()="Hubspot Companies"]'
    this.Add_Event_company_updated = '//h4[text()="Company Updated"]'
    this.Add_Filters_2 = '(//h1[text()="Add filter"])[2]'
    this.Add_Filters_hubspot_contacts = '//h4[text()="Hubspot Contacts"]'
    this.hubspot_contacts_pipeline = '//h4[text()="Hubspot Contact Pipeline"]'
    this.All_segments = '(//div[text()="All segments"])[1]'
    this.not_Set = '//div[@title="(Not Set)"]'
    this.identify_user = '//div[@title="Identified User Id"]'
    this.move_to = '(//div[text()="Move to"])[1]'
    this.New_folder = '//div[text()=" New Folder"]'
    this.create_newfolder = '//input[@placeholder="Eg- Folder 1"]'
    this.Edit_Folder = '//div[text()=" Edit Folder"]'
    this.Delete_Folder = '(//div[text()=" Delete Folder"])[1]'
    this.confirmbtn = '//span[text()="Confirm"]'
    this.Folder_Delete = '//span[text()="Folder Deleted"]'
    this.delete_segment = '//div[text()="Delete segment"]'
    this.confirmbtn1 = '(//span[text()="Confirm"])[2]'
    this.In_Hubspot = '//span[text()="In Hubspot"]'
    this.Insight_customdate = '//h4[text()="In Hubspot"]//preceding::button[1]'
    this.Last_Week = '//a[text()="Last Week"]'
    this.Account_currently = '//h4[text()="Accounts currently in segment"]//following::span[1]'
    this.Account_high_engagement = '//h4[text()="Accounts with High engagement"]//following::span[1]'
    this.Website_sessions = '//h4[text()="Website sessions"]//following::span[1]';
    this.Total_Website_sessions = '//h4[text()="% of total website sessions"]//following::span[1]'
    this.Total_visitor_segment = '//h4[text()="Total visitors from segment"]//following::span[1]'
    this.Total_PageViews = '//h4[text()="TotalPageViews"]//following::span[1]'
    this.Marketing_qualified = '(//h4[text()="Marketing Engagement Analysis"]//following::span)[1]'
    this.sales_qualified = '(//h4[text()="Sales Opportunity Analysis"]//following::span)[1]';
    this.Opportunity_Created = '(//h4[text()="Opportunity Created"]//following::span)[1]';
    this.Pipeline_Created = '(//h4[text()="Pipeline Created"]//following::span)[1]'
    this.Average_Deal_Size = '(//h4[text()="Average Deal Size"]//following::h2)[1]'
    this.Revenue_Booked = '(//h4[text()="Revenue Booked"]//following::h2)[1]'
    this.Close_Rate = '(//h4[text()="Close Rate (%)"]//following::h2)[1]'
    this.Avg_Sales_Cycle_Length = '(//h4[text()="Avg Sales Cycle Length"]//following::h2)[1]'
    this.Last_Month = '//a[text()="Last Month"]'
    this.Last_Quarter = '//a[text()="Last Quarter"]'
    this.select_custom_range = '//a[text()="Select Custom Range"]'
    this.Preview_Month1 = '//input[@placeholder="Start date"]//following::button[2]';
    this.Start_Date1 = '(//div[text()="2"])[1]';
    this.End_Date1 = '(//div[text()="15"])[2]';
    this.Adpilot = '//h4[text()="AdPilot"]';
    this.Add_new_rule = '//div[text()="Add New Rule"]';
    this.SyncNewAudience = '//div[text()="Sync New Audience"]';
    this.Campaign = '//h4[text()="Campaign"]';
    this.select_Campaign = '//span[text()="Select Campaigns"]';
    this.select_Campaign_value = '//div[text()="TD-MessageAd-Conversions-MatchedAudience-US-0309"]';
    this.select_Campaign_value1 = '//div[text()="TD-Spotlight-WebsiteVisits-Gromo-0609"]';
    this.select_Campaign_value2 = '//div[text()="TD-MessageAds-WebsiteVisits-Gromo-0609"]';
    this.adpilot_editicon = '//span[@aria-label="edit"]';
    this.adpilot_edit_searchbar = '//textarea[text()="Account level pacing"]';
    this.adpilot_arrow_left = '//span[@aria-label="arrow-left"]';
    this.adpilot_publish = '//div[text()="Publish"]';
    this.New_Campaign = '//h4[text()="New Campaign"]';
    this.All_account_toogle = '//h1[text()="Set custom rules based on advanced account conditions"]//preceding::button[1]';
    this.campaign_add_filter = '//h1[text()="Add filter"]';
    this.hubspot_company_pipeline = '//b[text()="Hubspot Company Pipeline"]';
    this.companies_lifecycle = '//h4[text()="companies-lifecycle-pipeline"]';
    this.total_clicks_cap = '(//th[text()="Total Clicks Cap"])[2]//following::input[1]';
    this.total_clicks_cap1 = '(//th[text()="Total Clicks Cap"])[2]//following::input[2]';
    this.total_clicks_cap2 = '(//th[text()="Total Clicks Cap"])[2]//following::input[3]';
    this.total_clicks_cap3 = '(//th[text()="Total Clicks Cap"])[2]//following::input[4]';
    this.total_clicks_cap4 = '(//th[text()="Total Clicks Cap"])[2]//following::input[5]';
    this.total_clicks_cap5 = '(//th[text()="Total Clicks Cap"])[2]//following::input[6]';
    this.campanies_active_status = '//h4[text()="New Group Campaign"]//following::span[1]';
    this.campanies_meatball_icon = '//h4[text()="New Group Campaign"]//following::span[4]';
    this.delete_meatball_icon = '//h4[text()="Active"]//following::button[2]';
    this.delete = '//span[text()="Delete"]';
    this.active_status = '//h4[text()="Active"]//following::button[1]';
    this.discard_changes = '//div[text()="Discard Changes"]';
    this.advanced_custome_rule = '//h4[text()="Set advanced custom rules"]//following::div[3]';
    this.campaign_group = '//h4[text()="Campaign Group"]';
    this.select_campaign_group = '//span[text()="Select Campaign Groups"]';
    this.select_Campaigngroup_value = '//div[text()="BOFU - Matched Audience"]';
    this.select_Campaigngroup_value1 = '//div[text()="BOFU Prospecting"]';
    this.select_Campaigngroup_value2 = '//div[text()="TD-Prospecting-Gromo+Agencies"]';
    this.New_Group_Campaign = '//h4[text()="New Group Campaign"]';
    this.All_Ad_Account = '//h4[text()="All Ad Accounts"]';
    this.All_Ad_Campaign = '//h4[text()="All Ad Accounts"]';
    this.AllAd_meatball_icon = '//h4[text()="All Ad Accounts"]//following::button[2]';
    this.New_Campaign_Pause = '(//button[@role="switch"])[1]';
    this.pause = '//span[text()="Pause"]';
    this.Paused = '(//span[text()="Paused"])[1]';
    this.new_campaign_pause1 = '(//h4[text()="New Campaign Pause"])[1]';
    this.confirm_publish = '//span[text()="Confirm Publish"]';
    this.active = '(//span[text()="Active"])[1]';
    this.Remove_rule = '//span[text()="Remove rule"]';
    this.segment_used = '(//div[contains(text(),"segments used")]//following::span)[1]'
    this.plans_billing = '(//h4[text()="Plans & Billing"])[1]'
    this.Upgrade = '//div[text()="Upgrade"]'
    this.Basic_add_btn = '(//h3[text()="Basic"]//following::button)[1]'
    this.Qty = '(//span[text()="Qty"])[1]'
    this.Qty1 = '(//span[text()="Qty"])[2]'
    this.Qty2 = '(//span[text()="Qty"])[3]'
    this.Qty3 = '(//span[text()="Qty"])[4]'
    this.Qty4 = '(//span[text()="Qty"])[5]'
    this.Qty_value = '(//div[contains(text(),"2")])[1]'
    this.Qty_value1 = '(//div[contains(text(),"2")])[2]'
    this.Qty_value2 = '(//div[contains(text(),"2")])[3]'
    this.Qty_value3 = '(//div[contains(text(),"2")])[4]'
    this.Qty_value4 = '(//div[contains(text(),"2")])[5]'
    this.proceed_to_checkout = '//span[contains(text(),"Proceed To Checkout")]'
    this.subscribe = '//span[contains(text(),"Subscribe")]'
    this.Growth_add_btn = '(//h3[text()="Growth"]//following::button)[1]'
    this.project_name = '//h4[text()="Kamali k"]//following::h4[text()="test 12345"]'
    this.user_name = '(//div[text()="kamali_tdfect@factors.ai"])[1]'
    this.project_name1 = '//h4[text()="Kamali k"]//following::h4[1]'
    this.switch = '//span[text()="Switch"]'
    this.moveto = '//*[text()="Move to"]'
    this.Delete_segment = '//*[text()="Delete segment"]'
    this.select_event1 = '//input[@placeholder="Select Event"]//following::div[3]'
    this.company_domains_new = '(//div[@title="Company Domain"])[1]'
    this.Company_Domain_Delete = "//h4[text()='Company Domain']//following::button[1]";
    this.Email_Delete = "//h4[text()='email']//following::button[1]";
    this.SelectFirst = '//h4[text()="Select:"]//following-sibling::span';
    this.SelectProperty = '#rc_select_2';
    this.selectproperty1 = ':nth-child(2) > :nth-child(3) > .ant-select > .ant-select-selector > .ant-select-selection-item';
    this.selectproperty2 = '(//div//div//span//input)[4]';
    this.Linkedin_Audience = '//h4[text()="Linkedin Audience Sync"]';
    this.select_factors_segment = '//th[text()="Factors segment to sync "]//following::span[1]';
    this.select_audiences_linkedin = '//th[text()="LinkedIn Audience to sync"]//following::input[2]';
    this.Engaged_linkedin = '//div[text()="Engaged on LinkedIn"]';
    this.Testing_audience = '//div[text()="Test audience | Third-party: Factors AI"]';
    this.edit_audience_sync = '//textarea[text()="Untitled audience sync"]';
    this.audience_sync_meta_icon = '(//h4[text()="New audience sync"])[1]//following::button[1]';
    this.Edit_workflow = '//a[text()="Edit"]';
    this.linkedin_sync_status = '//h2[text()="LinkedIn Sync Status"]';
    this.remove_workflows = '//span[text()="Remove workflow"]';
    this.linkedin_refresh_icon = ".mr-1 > .ant-btn"
    this.linkedin_search_icon = ".justify-end > .justify-between > .ant-btn"
    this.linkedin_search_report = '//input[@placeholder="Search reports"]'
    this.audience_sync_meta_icon1 = '(//h4[text()="New audience sync"])[1]';
    this.LinkedIn = '//button[text()="LinkedIn"]';
    this.Linkedin_conversion = '//input[@placeholder="Search"]//following::h4[text()="LinkedIn Conversion (CAPI)"]';
    this.use_this_workflow = '//span[text()="Use this workflow"]';
    this.test_capi = '(//div[text()="test capi"])[1]';
    this.stream_event = '(//span[@class="ant-select-selection-item"])[1]';
    this.First_Name = '(//span[text()="First Name"]//following::div)[4]';
    this.Hubspot_Contact_Contact_Unworked = '//div[@title="Hubspot Contact Contact Unworked"]';
    this.Last_Name = '(//span[text()="Last Name"]//following::div)[4]';
    this.Job_Tittle = '(//span[text()="Job Title"]//following::div)[4]';
    this.Company_Name = '(//span[text()="Company Name"]//following::div)[4]';
    this.Country_Code = '(//span[text()="Country Code"]//following::div)[4]';
    this.From_Title = '//div[@title="Form Type"]';
    this.HubspotContact = '//div[@title="Hubspot Contact Marketing Contact Until Next Update"]';
    this.untitled_workflow = '//textarea[contains(text(),"LinkedIn Conversion (CAPI)")]';
    this.untitled_workflow_icon = '(//h4[text()="LinkedIn Conversion (CAPI)"])[1]/div';
    this.new_linkedin_workflow_metaicon = '(//h4[text()="New linkedin workflow"]//following::button[1])[1]';
    this.Add_a_Filter = '//span[text()="Add a filter"]';
    this.new_linkedin_workflow_metaicon1 = '(//h4[text()="New linkedin workflow"])[1]';
    this.custom_event_name = '[aria-label="edit"]';
    this.Save_changes2 = '//span[text()="Save Changes "]';
    this.Save_button1 = '(//span[text()="Save"])[1]/button';
    this.All_segments1 = '(//span[text()="All Segments"])[1]';
    this.Add_filters3 = '//span[text()="New folder"]';
    this.save_newfolder = '(//*[text()="Save"])[1]';
    this.save_newfolder1 = '(//*[text()="Save"])[2]';
    this.Map_user_properties_firstname = '(//div[text()="Hubspot Contacts"]//following::div)[1]';
    this.Folder_created = '//*[text()="Folder created"]';
    this.Save_segments1 = '//span[text()="Save Segment "]';
    this.companycountry = '//div[text()="Company Country"]';
    this.insightcalender = ".ant-btn ant-btn-default ant-dropdown-trigger datepicker-minWidth"
    this.Add_filters2 = '(//*[text()="Add filter"])[2]';
    this.Albania = '//div[@title="Albania"]';
    this.Apply_filter = '//span[text()="Apply filter"]';
    this.New_folder1 = '//span[text()="New folder"]';
    this.Delete_Folder1 = '(//div[text()=" Delete Folder"])[2]';
    this.UserProperty_Delete = '//h4[text()="is_email_verified"]//following::button[1]';
    this.IsPageView = '[title="Is Page View"]';
    this.CampaignID = '[title="Campaign ID"]';
    this.EventProperties_Delete = '//h4[text()="Company Enriched"]//following::button[1]';
    this.Back = '//span[text()="Back"]';
    this.CompanyEnriched = '[title="Company Enriched"]';
    this.select_folder = "//span[text()='Please Select']";
    this.Lock_Symbol = '(//*[local-name()="svg" and @data-icon="lock-keyhole"])[1]';
    this.Search_Input = '(//input[@placeholder="Search"])[1]';
    this.Country_Breakdown = '[title="Company Country"]';
    this.Login_Event = '//h4[text()="LOGIN"]';
    this.Save_Segment = '//h1[text()="Save Segment"]';
    this.Zoho_Templete = '//input[@placeholder="Search"]//following::h4[text()="Add or update Zoho companies"]';
    this.Templete_Popup = '.ant-modal-content';
    this.PerformedEvent = '//h4[text()="Account has performed event"]//following::span[2]';
    this.Zoho_Connection = '(//div[text()="Integrate Zoho CRM"]//following::h4)[1]';
    this.Select_Property = '(//h4[text()="Additional fields (Optional)"]//following::input)[1]';
    this.Select_Property1 = '(//h4[text()="Additional fields (Optional)"]//following::input)[2]';
    this.Select_Property2 = '(//h4[text()="Additional fields (Optional)"]//following::input)[3]';
    this.Select_Property3 = '(//h4[text()="Additional fields (Optional)"]//following::input)[4]';
    this.Selete_Property_Option = '[title="Email"]';
    this.Selete_Property_Option1 = '[title="Form ID"]';
    this.AccountName = '[title="Account Name"]';
    this.AccountSite = '[title="Account Site"]';
    this.Save_Report = '(//*[text()="Save"])[3]';
    this.Edit_workflow1 = '//a[text()="Edit workflow"]';
    this.Campaign_MoreOption = '//h4[text()="Active"]//following::button[2]';
    this.CreateNewSegment = '//span[text()="Create New Segment"]';
    this.active_Toggle1 = '//h4[text()="Active"]//following::button[1]/div';
    this.FolderNameField = '[placeholder="Eg- Folder 1"]';
    this.PageView = '//span[text()="Page View"]';
    this.AddRule = '(//span[text()="Add rule"])[1]';
    this.Add_Rule1 = '(//span[text()="Add rule"])[2]';
    this.Add_Rule2 = '//h4[text()="Campaign details"]//following::span[text()="Add rule"]';
    this.Add_Rule3 = '//h4[text()="G2 page details"]//following::span[text()="Add rule"]';
    this.HubSpotForms = '//span[text()="HubSpot Forms"]';
    this.PageViewOption = '(//*[name()="svg" and @data-icon="trash"])[1]//preceding::span[3]';
    this.PageViewOption1 = '(//*[name()="svg" and @data-icon="trash"])[2]//preceding::span[3]';
    this.PageUrlIs = '[title="Page URL is"]';
    this.PageUrlContains = '[title="Page URL contains"]';
    this.URLInput = '[placeholder="Enter a value"]';
    this.URLInput2 = '(//h4[text()="Form submission details"]//following::input[@placeholder="Enter a value"])[1]';
    this.URLInput3 = '//h4[text()="Campaign details"]//following::input[@placeholder="Enter a value"]';
    this.URLInput4 = '//h4[text()="G2 page details"]//following::input[@placeholder="Enter a value"]';
    this.Formtitleis = '[title="Form title is"]';
    this.Formtitlecontains = '[title="Form title contains"]';
    this.factorsPageURL = '[title="www.factors.ai"]';
    this.NewSignupForm = '[title="New Signup Form"]';
    this.SalesforceCampaigns = '//span[text()="Salesforce Campaigns"]';
    this.Campaignnameis = '[title="Campaign name is"]';
    this.Campaignnamecontains = '[title="Campaign name contains"]';
    this.LinkedInAds = '//span[text()="LinkedIn Ads"]';
    this.G2Intent = '//span[text()="G2 Intent"]';
    this.Pagetitleis = '[title="Page title is"]';
    this.Pagetitlecontains = '[title="Page title contains"]';
    this.URLoption = '((//div[@role="listbox"])[2]//following::div[6])[1]';
    this.URLoption1 = '((//div[@role="listbox"])[3]//following::div[6])[1]';
    this.SegmentTitle = '//h1[@class="ant-typography text-lg font-semibold editable-title"]';
    this.Touchpoints_Metaball = '(//tbody//tr//td[3]//button)[1]';
    this.PageViewURL = '[title="staging-app.factors.ai"]';
    this.scoreLeavePopup = '.ant-modal-content';
    this.DiscardandLeave = '//span[text()="Discard and Leave"]';
    this.StayonPage = '//span[text()="Stay on Page"]';
    this.BackArrow = '(//*[name()="svg" and @data-icon="arrow-left"])';
    this.Configurations = '//div[text()="Configurations"]';
    this.BillingCity = '(//div[@title="Billing City"])[2]';
    this.KPITOANALYSE = '(//h4[text()="KPI TO ANALYSE"])[2]';
    this.EVENTS = '(//h4[text()="EVENTS"])[2]';
    this.FUNNEL = '(//h4[text()="EVENTS PERFORMED IN"])[2]';
    this.PROFILESTOANALYSE = '(//h4[text()="PROFILES TO ANALYSE"])[2]';
    this.AllsegmentMenu = '//h4[text()="All Accounts"]//following::div[6]';
    this.EditsegmentDetails = '//div[text()="Edit segment Details"]';
    this.Hubspot_InsightLoad = '//h4[text()="In Hubspot"]//following::div[3]';
    this.NewAlert = '//span[text()="New Alert"]';
    this.StartfromScratch = '//h4[text()="Start from Scratch"]';
    this.Hubspot_template_Option = '//button[text()="Hubspot"]';
    this.Salesforce_template_Option = '//button[text()="Salesforce"]';
    this.Zoho_template_Option = '//button[text()="Zoho"]';
    this.ChooseaTemplate = '//h4[text()="Choose a Template"]';
    this.SelectTemplate = '//h4[text()="One of your accounts just visited the pricing page"]';
    this.InterestGroups = '//div[text()="Interest Groups"]';
    this.AddNewGroup = '//span[text()="Add New Group"]';
    this.SetRules = '//h4[text()="Set Rules"]';
    this.AddEvent = '//h1[text()="Add event"]';
    this.QuickFilters = '//span[text()="Filter"]//following::button[2]';
    this.AccountOwner = '[aria-label="Account Owner"]';
    this.SelectValues = '//span[text()="Select Values"]';
    this.VisitedPricing = '[aria-label="Visited Pricing"]';
    this.SQLsandOpps = '[aria-label="SQLs and Opps"]';
    this.QuickSearchTitle = '//span[text()="Hide Filters"]//following::div[3]';
    this.PreviewInfo = '.preview-info';
    this.DownloadCSV_Popup = '.ant-modal-content';
    this.SmartReach = '(//h4[text()="Smart Reach"])[2]';
    this.LinkedInaudiencesync = '//h4[text()="LinkedIn audience sync"]';
    this.CustomEvents = '//span[text()="Custom Events"]';
    this.Filter = '//span[text()="Filter"]';
    this.channelGroup = '//div[text()="Channel Groups"]';
    this.ChannelValue = '#value';
    this.EditProperty = '//a[text()="Edit Property"]';
    this.RemoveProperty = '//a[text()="Remove Property"]';
    this.panelemailTracking = '//div[contains(@id,"panel-emailTracking")]';
    this.EmailClicks_container = '//div[contains(@class,"EmailClicks_container")]';
    this.Createatouchpointusing = '//h4[text()="Create a touchpoint using"]';
    this.CampaignGroups = '//div[text()="Campaign Groups"]';
    this.CampaignTitle = '//h3[text()="New Custom Dimension"]';
    this.ValueName = '[placeholder="Value"]';
    this.NewSelectProperty = '//span[text()=" Select Property"]';
    this.NameOption = '[title="name"]';
    this.Filtervalue = '//h4[text()="Filters"]//following::input[@type="text"]';
    this.Filtervalue1 = '(//h4[text()="Filters"]//following::input[@type="text"])[2]';
    this.EditProperty1 = '//span[text()="Edit Property"]';
    this.RemoveProperty1 = '//span[text()="Remove Property"]';
    this.CampaignNameVerify = '//h4[text()="Display Name"]//following::h4[1]';
    this.PropertyMappingDisplayName = '#login_name';
    this.SelectEventMapping = '//h4[text()="Website Session"]//following::div[2]';
    this.UserPlatform = '[title="User Platform"]';
    this.AlertMsg = '[role="alert"]';
    this.AdvancedFilters = '//h1[text()="Advanced Filters"]';
    this.HubspotDeals = '[title="Hubspot Deals"]';
    this.Deals = '[title="Deals"]';
    this.chartName = '(//*[local-name()="svg" and @id="funnel-grouped-svg-chart"])//following::div[1]';
    this.Removefromthisboard = '//div[text()="Remove from this board"]';

  }
}

export default new locators();